### ISSUE TITLE
Disable requirement for Changelog module?

### ISSUE THREAD

**Issue by tbrockwood** [ironmonk88/monks-little-details#103]
Ever since this started requiring Changelog as part of the install, I've had nothing but problems and had to remove Little Details module entirely. I did a Find the Culprit multiple times on my setup, and every time, the issue came down to Changelog. Is there any way to run this without Changelog installed?

**Comment by theripper93** [comment]
can you describe what issues changelogs is causing? there should be nothing in the code that interacts with foundry at all outside of showing a dialog
