### ISSUE TITLE
Starting location token not seen by non-owners

### ISSUE THREAD

**Issue by ckdragons** [ironmonk88/monks-little-details#104]
It would seem that only the player (owner) of the character is able to see the shadowed start token of where their token started at the beginning of their turn. The GM is unable to see these shadowed tokens for PCs as they move, only the shadowed tokens of the NPCs as the GM moves them. Is there an option I'm missing?

**Comment by ironmonk88** [comment]
I'd noticed that earlier.  Only the person moving the token would see it.  So if the GM moved the token, the player wouldn't see it.
Should be fixed for the next release.

**Comment by ironmonk88** [comment]
Should be fixed in the last release.
