### ISSUE TITLE
Combat Tracker pop-out in new session?

### ISSUE THREAD

**Issue by KJTailor** [ironmonk88/monks-little-details#105]
Hi Ironmonk,

I have it happening sometimes that a combat encounter spans beyond 1 session. When We start back up in the next session, the combat tracker is not popped out anymore. Is it possible to put in a button to trigger the combat tracker to pop out for those times?

cheers

**Comment by ironmonk88** [comment]
You can right click on the fist icon in the sidebar menu.
![image](https://user-images.githubusercontent.com/75920956/139598492-f7b72a4f-7e8c-4bd5-b754-0ca918360f1d.png)
That will popout the combat again.

**Comment by KJTailor** [comment]
Good to know. Thank you :)

**Comment by ironmonk88** [comment]
Closing this as the issue should be resolved.  Cleaning up tickets.
