### ISSUE TITLE
Unable to open the sidebar once collapsed when using the Fantasy UI module. [Bug]

### ISSUE THREAD

**Issue by Darkiller25** [ironmonk88/monks-little-details#106]
Hi! I'm not sure if it's one of the options specifically in your module that creates this issue, but after using Find The Culprit module, I found this one to be the problem. 

When using the normal Foundry UI, there's no issue, but since the collapse button moves at the bottom of the collumn on the right, it just disappears and it's not possible to reopen the sidebar (unless using F5).

Any idea how to fix this?

P.S. I'm on Foundry version 0.8.9 and Monk's little detail version 1.0.37

Thanks!

**Comment by professorx00** [comment]
I found the same issue. It almost feels like a feature but I don't think it is.

**Comment by Darkiller25** [comment]
Yup same here... it's sad because I really love the Fantasy UI (I find the icons to be clearer in purpose than the normal one).

**Comment by ironmonk88** [comment]
Sort of fixed it.  Fantasy UI isn't allowing me to reposition the expand button properly.
But I also added a setting so you can turn off the expand/collapse button being re-positioned.

**Comment by ironmonk88** [comment]
Setting was added in the last release.
As mentioned, I can't really fix it, but I did add the option to opt out of moving the expand/collapse button.
