### ISSUE TITLE
HUD Customizability?

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-little-details#11]
I love this mod, but I like to use custom HUD effects with the Condition Lab from the CUB module. That module will work with this one, but this one forces you to also use the default conditions as well, which means I've got nearly 70 icons in my HUD list now, many of which are duplicates. Any chance you can give us the option to turn the defaults off so we can only use our own custom icons?

Thanks!

**Comment by ironmonk88** [comment]
You should already be able to do that.
![DnDStatuses](https://user-images.githubusercontent.com/75920956/107140116-c6a52800-68d4-11eb-9092-f62abdd719f0.png)

With that unchecked, Little Details won't add any extra.

**Comment by ironmonk88** [comment]
I think this has been covered.  Closing the issue.
