### ISSUE TITLE
Turnmaker icon

### ISSUE THREAD

**Issue by Verthiss** [ironmonk88/monks-little-details#110]
Hi! 
I love the Combat Token Highlight feature but the icon you used is not the best, it has some ugly white borders and discolorations on the circles. I updated it to look nicer, feel free to use it :)
![turnmarker](https://user-images.githubusercontent.com/70172408/136761907-89e9813b-b954-45d4-af64-3be54ebd8755.png)

**Comment by ironmonk88** [comment]
To be perfectly honest... I don't actually use the image included with Little Details.
But the one included was pretty crappy.  Thank you so much for updating it.

**Comment by ironmonk88** [comment]
Should be added to the latest release.  Again, than k you for the updated artwork.
