### ISSUE TITLE
Add option to _not_ sort Status Effects alphabetically

### ISSUE THREAD

**Issue by ksignorini** [ironmonk88/monks-little-details#112]
I worked hard to arrange my Status Effects in the order I want them using the CUB Condition Lab. As much as I LOVE what you do with the naming and colourizing, Little Details rearranges all my organized effects alphabetically.

Would you please consider an option to turn the alphabetical sorting on/off?

Thanks and keep up the awesome work!

**Comment by ironmonk88** [comment]
Should be fixed in the last release.
