### ISSUE TITLE
Sorting incorrectness when using Combat Utility Belt's Enhanced Conditions

### ISSUE THREAD

**Issue by mezmor** [ironmonk88/monks-little-details#115]
I want to preface this with accolades for the fantastic piece of software you've written. Fantastic work.

I've found odd sorting behavior in both Row and Column sorting. I've tried to include setting states that are relevant, but I'm not actually sure what all is relevant - I welcome any questions about my configuration.

**Incomplete Preconditions**
Combat Utility Belt enabled
Combat Utility Belt's Enhanced Conditions enabled
Combat Utility Belt's 5e extended conditions imported (steps for importing [found here](https://youtu.be/BRlWhbw0mbk?t=491))
MidiQol enabled
Monk's Little Details Add DnD statuses disabled

**Column Sorting** - Priority Fix.
[Example screenshot](https://i.imgur.com/As09hR3.png)
This is probably the most bizarre. It's all over the place, and I have no explanation for what's going on. I defer to the screenshot.

**Row Sorting** - Has workaround, implementation detail.
[Example screenshot](https://i.imgur.com/ze2NfZV.jpeg)
Row sorting is correct for the majority of conditions. I noticed that one of the imported conditions "Injured" is placed after "Bardic Inspiration" and before "Bless". When examining the conditions in detail, I found that the "Injured" condition does not have a condition reference, and uses the "icons/svg/blood.svg" icon. 
My workaround is to rename it to "Bloodied" so that it fits.

Would it be possible to sort by condition name?

**Comment by ironmonk88** [comment]
Fixed a bug with the column sorting.
But in general... I'm at the mercy of how the system sends the information.  And most of the time all I get is the filename, rather than condition information.
The code is updated so that if a system sends more information then it will sort properly, but until that moment, there's not a lot I can do about it.
