### ISSUE TITLE
Starting position not displayed correctly (or GM sees different starting position than player)

### ISSUE THREAD

**Issue by sasquach45932** [ironmonk88/monks-little-details#116]
Dear ironmonk88,

When "starting position display" is  enabled the following issue  happens.  Shadow token placed incorrect position. It does not happen if I use the arrow keys, only when using mouse.  Sometimes I see it is OK, GM says he sees the token in incorrect position.

Hoping you can fix it, Thank you for your add-ons, they are very useful. 

Regards,

Sasquach

![Starting](https://user-images.githubusercontent.com/92884040/140653212-0c1c21aa-bf1c-476c-baf1-1131927f9bd5.png)
![Arriving](https://user-images.githubusercontent.com/92884040/140653221-d12794ab-d4eb-49d5-8c65-970819fe53b2.png)

**Comment by ironmonk88** [comment]
Should be fixed in the last release.
