### ISSUE TITLE
Speaker Icon Missing From NPC Sheet

### ISSUE THREAD

**Issue by Amd321** [ironmonk88/monks-little-details#118]
When activated, the speaker icon for the Actor Sound Effect option is not appearing on NPC sheets. Because of this, the FilePicker cannot be accessed to select which sounds are played from a token. Sheets that have been previously configured, still have an option to play those sounds from tokens.

**Comment by davidhawbecker** [comment]
I can confirm this as well. I have actually used the token sound feature quite a bit and it appears to be missing now.

**Comment by ironmonk88** [comment]
Should be fixed in the last release.

**Comment by davidhawbecker** [comment]
Awesome. I will check it out tonight. Thanks for all the great work on this stuff. Really does make the game even better.
