### ISSUE TITLE
[BUG] New "Turn dead invisible" boolean doesn't work as expected

### ISSUE THREAD

**Issue by DarKDinDoN** [ironmonk88/monks-little-details#119]
Hello,

This new feature doesn't seem to be working.
Whether the checkbox is checked or not, the monsters always turn invisible for the players.

FVTT 0.8.9
5e 1.5.3
Monks Little Details 1.0.39

**Comment by Cup-of-Coffee** [comment]
I am also having this issue.

**Comment by ironmonk88** [comment]
New settings were added to bloodsplat so players could also see the token.
