### ISSUE TITLE
Dominant Scene Colours as seperate module?

### ISSUE THREAD

**Issue by Danii0206** [ironmonk88/monks-little-details#12]
Hi,

I would like to use the Dominant Scene Colours part of this collection, but not the other things. I don't play d&d and some of them might interfere with things my system does. So would it be possible to have that as an extra module?

Kind regards
Danii

**Comment by ironmonk88** [comment]
https://raw.githubusercontent.com/ironmonk88/monks-color-palette/master/module.json
Won't publish it as a regular module, but using that link you should be able to add it manually.

**Comment by ironmonk88** [comment]
Hopefully that worked.  Closing the ticket.  :-)

**Comment by Danii0206** [comment]
Works like a charm. Thank you! :-)
