### ISSUE TITLE
combat hightlight image setting does not get shown after save

### ISSUE THREAD

**Issue by Tupsi** [ironmonk88/monks-little-details#124]
The setting can be used to change the image, but the value of it does not get reflected in the gui when you reopen the actor again as it defaults to the default.
![image](https://user-images.githubusercontent.com/3730499/145715425-62406a27-8d66-4921-917d-c7ef9c707aed.png)

although it sticks to the actor as can be seen when exporting the .json of an actor. Just entereing nothing does in turn does not reset it to a default value.
As nothing is even put back into the edit field one is having a hard time resetting the field.
(Finding your default marker and putting it into the field once does the trick, although it is now an actual value but not undoing the previous one)
      "monks-little-details": {
        "displayBarsCombat": null,
        "token-highlight": "modules/monks-little-details/icons/turnmarker.png",
        "bloodsplat-colour": "#ac2f2f",
        "glyph": "ÿ"
      },

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
