### ISSUE TITLE
Duplicate Conditions

### ISSUE THREAD

**Issue by jabbamonk** [ironmonk88/monks-little-details#127]
When I activate the module, I love that the conditions all have names next to them now and really like some of the new icons ... BUT, there are tons of duplicates (i.e. blinded). I am also running Combat Utility Belt, which has the Conditions Lab ... so I wonder if there is a compatibility issue. Is there a way to get rid of duplicates, and get this to work with the Conditions Lab (I'd love to be able to modify the new conditions you've added, and get rid of the duplicates)?  I'm hoping its a simple fix in the settings ... let me know. Thanks!

**Comment by DivertedCircle** [comment]
I've noticed the same issue of duplicate conditions but I'm not convinced it's Combat Utility Belt and Monk's Little Details conflicting. I've found that running them together doesn't cause the duplicates but running DFred's Convenient Effects with them does cause duplicates.

**Comment by macdhollister** [comment]
Still an issue, I also noticed that the cause is DFred's Convenient Effects.

**Comment by mvanduijvenvoorde** [comment]
I have the same issue, will also add it to the other project

**Comment by ironmonk88** [comment]
Added the option to customize the additional statuses in the latest release.
