### ISSUE TITLE
[bug?] With config "Do not open combat window", the Combat Tracker tab still gets opened

### ISSUE THREAD

**Issue by yjeroen** [ironmonk88/monks-little-details#136]
If I set Popout Combat Dialog to "**Do not open combat window**" (because I use combat carousel), monks-little-details still switched the GM from the chat tab to the combat tracker tab.

Is this a bug?
If it's intended, could this be a setting in the Module Settings?

**Comment by ironmonk88** [comment]
Added the setting to the latest version.
The setting "Do not open combat window" pertains to the combat dialog opening, not the tab switching to the combat tab.
