### ISSUE TITLE
slowness (may be subjective) and errors when Monks Little details is enabled and Try to open "Default Token Config"

### ISSUE THREAD

**Issue by galaara98** [ironmonk88/monks-little-details#137]
if only Monks Little Detail is enabled, and you open Default Token Configuration in the Core settings, the game pauses for a bit, and an error is thrown in the console.  If Monks Little Details is not enabled, the error does not happen.

TypeError: Error thrown in hooked function '' for hook 'renderTokenConfig': app.object.getFlag is not a function
    at combat-marker.js:134:201
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at DefaultTokenConfig._render (foundry.js:3114:13)
    at async DefaultTokenConfig._render (foundry.js:3761:5)
onError @ foundry.js:316
_call @ foundry.js:298
call @ foundry.js:279
_render @ foundry.js:3114
await in _render (async)
_render @ foundry.js:3761
render @ foundry.js:3018
render @ foundry.js:54532
_onClickSubmenu @ foundry.js:55345
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

if Monks Little details is enabled and libwrapper is enabled, the error is a bit more clear that monks is the culprit
TypeError: app.object.getFlag is not a function
[Detected 1 package: monks-little-details]
    at combat-marker.js:134:201
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at DefaultTokenConfig._render (foundry.js:3114:13)
    at async DefaultTokenConfig._render (foundry.js:3761:5)

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
