### ISSUE TITLE
Bug on checkCombatTurn()'s last turn of a round

### ISSUE THREAD

**Issue by mclemente** [ironmonk88/monks-little-details#14]
https://github.com/ironmonk88/monks-little-details/blob/main/monks-little-details.js#L638-L639

1) Create a combat with 2 combatants.
2) Pass turn.
3) Pass turn.

`nxtentry` (Line 646) will be undefined because `curCombat.turns` only has 2 elements and `next` will be 2, so `curCombat.turns[next]` will return undefined.
Solution (add to line 640):
```javascript
else if (next == curCombat.turns.length) next = 0;
```
But that doesn't take into account that the first combatant might be skipped, so you probably have to rewrite findNext() to check if it's the last turn of a round instead.

**Comment by ironmonk88** [comment]
Which version of little details are you using?

**Comment by mclemente** [comment]
1.0.11

**Comment by ironmonk88** [comment]
Ohhhh... found it.  
Line 639 should read `next = findNext(-1);`
If set to 0 it'll skip over 0 and find the next one after that.

Thank you for catching that!

**Comment by ironmonk88** [comment]
Should be fixed in 1.0.12
