### ISSUE TITLE
No drag walls together toggle

### ISSUE THREAD

**Issue by Orionox** [ironmonk88/monks-little-details#140]
Just like the title says, I do not see a toggle for dragging walls together.

I also don't see a "find my token" button despite having that toggled

**Comment by ironmonk88** [comment]
The dragging wall points together has moved.
https://foundryvtt.com/packages/monks-wall-enhancement

I'm just horrible about updating my documentation.

And Find my Token is only available for the players as the GM owns all the tokens so it doesn't make a lot of sense to cycle through all of them.

**Comment by ironmonk88** [comment]
Closing this as the documentation has been updated.  Still needs some work, but switch to Wall Enhancements has been included.
