### ISSUE TITLE
Window Vanishes

### ISSUE THREAD

**Issue by grungyape** [ironmonk88/monks-little-details#141]
Not sure what causes it, but if the pop-out combat vanishes, I am not seeing a way to restore it. Is this an issue, or am I a dunce?

**Comment by ironmonk88** [comment]
Right click on the combat tab.  :-)
![image](https://user-images.githubusercontent.com/75920956/150654896-b8ff73f4-a705-4171-a1ff-93062a2cb1d2.png)

It's part of core and you can open the other tabs that way too... although some of them don't really make much sense to do it that way.

**Comment by grungyape** [comment]
Ya, I was not clear.  I can get back to the combat tab built into the side, however the pop up window vanishes.

**Comment by ironmonk88** [comment]
Right click the icon.  Not left click.

**Comment by grungyape** [comment]
Holy shit, thank you.  I'm sorry I didn't figure this out on my own.  Again, thank you.

**Comment by ironmonk88** [comment]
Closing this as I believe the solution has been found.
