### ISSUE TITLE
Initiative Order

### ISSUE THREAD

**Issue by IronWarjack** [ironmonk88/monks-little-details#142]
Per the PHB pg 189, the DM (and players) can adjust init order if characters are tied.  I see no way to do this.  The order does not appear to be drag/drop, nor include any up/down move tool

**Comment by ironmonk88** [comment]
I would recommend the module https://foundryvtt.com/packages/combat-enhancements.
That's the one I use.

**Comment by ironmonk88** [comment]
Closing the issue as there are other module solutions that handle this.
