### ISSUE TITLE
Quality of Life feature:  NPC Sounds description

### ISSUE THREAD

**Issue by galaara98** [ironmonk88/monks-little-details#144]
Current description in settings says

Actor Sound Effects
Add a button to the character sheet and TokenHUD to play a sound effect

But documentation makes it clear this is currently only intended for NPCs.

I would propose changing the in-game settings description to say
NPC Actor Sound Effects (or keep it as Actor so long as the next sentence is cleared up)
Add a button to the NPC character sheet and TokenHUD to play a sound effect

OR

Add the capability to other sheets (for instance I wouldn't mind it on vehicles [Zoom or horse sounds] or Loot [a jingle of coins or a shopkeep bell would be cool] and even PCs for a "catch phrase" recording)

**Comment by ironmonk88** [comment]
The option to add sounds to all character sheets was added awhile ago.  I've adjusted the text on the readme to reflect the changes, and will update the Foundry text on the next update.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
