### ISSUE TITLE
Invalid Manifest File

### ISSUE THREAD

**Issue by rmasoni** [ironmonk88/monks-little-details#15]
I'm not able to update or reinstall this module. Foundry says its manifest file is invalid.

```
Installation failed: The request to https://raw.githubusercontent.com/ironmonk88/monks-little-details/master/module.json did not provide a valid manifest file.
```

<img width="972" alt="image" src="https://user-images.githubusercontent.com/62244/108978989-f8eead80-7668-11eb-8669-274a854c1c1d.png">

**Comment by tagnullde** [comment]
Yep. Can confirm that too.

**Comment by JLtheking2** [comment]
Same here.

**Comment by ironmonk88** [comment]
This should be fixed now.  Not sure what was going on with that.  I suspect I pushed some changes that I shouldn't have.

**Comment by rmasoni** [comment]
I'm able to install it now. Thanks!
