### ISSUE TITLE
Reversion? Movement Key setting disappeared from mod in v9?

### ISSUE THREAD

**Issue by sharkbruhaha** [ironmonk88/monks-little-details#151]
Just updated to v9, and the Movement Key setting is no longer present? Is this a reversion, or intentional? It was incredibly useful :(.
v8, v1.0.39 of the mod: 
![image](https://user-images.githubusercontent.com/44031572/158292121-25b23225-09aa-48d9-8057-daa241b5d915.png)
v9, v1.0.44 of the mod: 
![image](https://user-images.githubusercontent.com/44031572/158292106-fc9dbc53-a1d4-4a35-9cf0-24659f9f3a36.png)

**Comment by ironmonk88** [comment]
v9 Added the option to edit Keys.  So it was moved under the core features.
"Configure Controls" on the settings tab.
![image](https://user-images.githubusercontent.com/75920956/158292563-1dcb11c1-0f4f-49d6-be88-716dc5fb4f5d.png)

**Comment by sharkbruhaha** [comment]
> v9 Added the option to edit Keys. So it was moved under the core features. "Configure Controls" on the settings tab. ![image](https://user-images.githubusercontent.com/75920956/158292563-1dcb11c1-0f4f-49d6-be88-716dc5fb4f5d.png)

ah! Thanks much! I hadn't realized that module settings for keys had all been moved over to there, thought it was still just the place for core-keys but everything just used the api now. Thanks much!
