### ISSUE TITLE
[Feature Request] Add a delay to the "Turn Dead Invisible" option.

### ISSUE THREAD

**Issue by ckdragons** [ironmonk88/monks-little-details#153]
Currently when this option is enabled, a defeated NPC token just disappears from the scene. The players do not have a chance to see it was defeated/dead. Adding a 1 or 2 second delay to when this occurs would allow the player to see the efforts of his work before the token is removed from his vision.

**Comment by ckdragons** [comment]
Edited to add to Title.

**Comment by ironmonk88** [comment]
Added a slight fade in/out of the bloodsplat and token icon when a character dies.  Makes it a little less abrupt.

**Comment by ckdragons** [comment]
Thank you for this update. Possible to switch the order so that the token is being turned in visible last. It looks great for the GM, however, the player still only sees the token disappear from view. The player doesn't see the skull icon on the token showing that it's dead. Maybe delay turning the token invisible for 3 seconds?
