### ISSUE TITLE
[FEATURE REQUEST] Panning to combatant

### ISSUE THREAD

**Issue by DarKDinDoN** [ironmonk88/monks-little-details#155]
Hello,

Kandashi made a module that as a lot in common with this one: https://github.com/kandashi/Next-Up/

This one is more maintained and offers more features. 😸 
One thing missing tho is the "panning to combatant" feature that NextUp has.
And that is the only reason I keep NextUp installed on my worlds.

![image](https://user-images.githubusercontent.com/1687854/159294133-5150747e-0b4d-4bc0-bc2c-cd4c7280850b.png)

Do you think it's possible to implement this feature into this module as well?
It makes sense since it goes along well with the Highlight/Marker feature.

**Comment by ironmonk88** [comment]
Should be added to the latest release.
