### ISSUE TITLE
Monks Little Details and Video Game Music (0.1.2)

### ISSUE THREAD

**Issue by galaara98** [ironmonk88/monks-little-details#158]
I have sent this to Video Game Music Dev Also (https://gitlab.com/Furyspark/foundryvtt-vgmusic/-/issues/7)
When Monks Little Details is active, Video Game Music (v0.1.2, but I believe previous ones also) does not engage Actor/Token Hype tracks when an Encounter starts.

Video Game Music does properly handle Ambient Scene Music.

When Monks little Detail is Disabled, and an encounter is started Video Game Music does play hype tracks.  If you re-enable Monks little detail then Video Game Music looses track of its music (it does not move to the next hype track when the encounter continues)

To Test:

Install the two modules.
   Set Video Game Music settings to "play area music"
create a scene.
in config of scene add Ambient Sounds (using the Video Game Music button, not the built-in ambience)
....   The Area is the Ambient track, the battle is the music that will play of "play area music" is set and an actor/token doesn't have a hype track.  You drag a playlist into the box, then pick a track if you so choose (for my test I always had a track)

create 2-3 PC or NPC actors, in their character sheets, at the top (near "Prototype Token") you will see Combat Music.  Click and add Hype track (again drag a playlist, then pick a track)
add actor's tokens to scene

Reload scene (should cause "Area" music to start)
create an encounter
add tokens to encounter
Roll initiatives
start encounter

WHAT SHOULD HAPPEN is 
1) the AREA music should pause
2) tokens who turn it is should play it's hypetrack, if token doesnt have hype track Battle Music from scene should play
    ... technically Video Game Music has proprieties so that in theory a Boss could have precedence over a player's music, but ignoring that.

Advancing the encounter should PAUSE hypetracks (so that when it is their turn again it picks up where left off) and unpause or start the next hypetrack 
Ending encounter should stop all Video Game Music, and unpause the Area Music.

When Monks Little Details is installed the Area Music works, but none of the Battle Hype Tracks do.

**Comment by galaara98** [comment]
I have isolated it down to monks little details: Next Turn Sound, Current Turn Sound, New Round Sound.  When I disable these (might not need all off)

**Comment by ironmonk88** [comment]
Maybe Video Game Music updated and fixed the issue?
I tried with the Next, Current and New Round Sounds enabled and it played those and the hype tracks as expected.

**Comment by ironmonk88** [comment]
Closing this as I can't replicate and there's been no further information.
