### ISSUE TITLE
Standardize module name

### ISSUE THREAD

**Issue by rmasoni** [ironmonk88/monks-little-details#16]
Nitpicking here, but the module name is missing an apostrophe.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/62244/109051309-26634780-76b9-11eb-96b2-ade03d705a69.png">

**Comment by ironmonk88** [comment]
Most things should be switched over.  Just waiting until the next release to clean up the remaining places.

**Comment by ironmonk88** [comment]
I think most of it should be updated now.
Monk's Scene Navigation still needs some updating.  Will update that on the next release.

**Comment by rmasoni** [comment]
Great! Thanks!
