### ISSUE TITLE
Disabling 'Your Next' and "Your Turn" prompts and sound does not disable them

### ISSUE THREAD

**Issue by TogaParty** [ironmonk88/monks-little-details#161]
I'm using something else to do this, and getting duplicate notifications and sound, even when I've disabled these features in Monk's Little Details.  This occurs in SW5e, but possibly others as well.

**Comment by ironmonk88** [comment]
I tried in both DnD5e and SW5e but it all works as expected.  Turning off the setting disabled the prompts, and same with the sounds.

**Comment by ironmonk88** [comment]
Closing this as I can't replicate and there's been no further information.
