### ISSUE TITLE
[Bug & Request] M is for Movement

### ISSUE THREAD

**Issue by Quidam2k** [ironmonk88/monks-little-details#162]
Holding down M doesn't seem to be working for some of my players. I think it might be a Mac issue. Also, one of my players would appreciate a checkbox in the settings to make that the default as opposed to requiring a key to be held down every time he moves his token.

**Comment by ironmonk88** [comment]
The movement key isn't available for the player.  And shouldn't be.  It can get them into a lot of trouble.
The M key doesn't respect walls, so the players could literally place themselves anywhere on the map.
It's just meant for GM's to reposition the players if they go to a different section on the map.

If you want to speed up the movement speed, I'd recommend the module [Token Ease](https://foundryvtt.com/packages/token-ease).  That being said, I know that Foundry itself has mentioned that it might add core support for adjusting movement speed, but I have no idea when that would happen.

**Comment by Quidam2k** [comment]
Ah, yes, I can see the sense in that. Thank you for clarifying. I'll look into the module you recommend.

**Comment by ironmonk88** [comment]
Closing as the issue has been addressed.
