### ISSUE TITLE
[BUG] "Sort Statuses: Columns" randomly sorts when changing statuses

### ISSUE THREAD

**Issue by JohnnyQuest1983** [ironmonk88/monks-little-details#163]
Foundry version 9.268
PF2E version 3.8.4.11118
Module version: 1.0.47

I'm running this on a new empty world with the Pathfinder 2e system.

With "Sort Statuses: Columns" selected, left clicking to add a status or right clicking to remove a status causes the status sorting to randomise. I can't see a logic behind the new sorting, and it randomises with every click.

"Sort Statuses: Rows" works perfectly.

Initial correct column sort:
![image](https://user-images.githubusercontent.com/12629730/163595895-65bc08ab-8cc7-432c-8e9e-c5475486ae7e.png)

Left Clicked "Sickened":
![image](https://user-images.githubusercontent.com/12629730/163596034-48fa39a3-1146-408d-8af4-a83172611e86.png)

Right Clicked "Sickened":
![image](https://user-images.githubusercontent.com/12629730/163596065-70444ef4-a11c-4bb4-b869-f4e95aaa6055.png)

**Comment by ironmonk88** [comment]
Sort of fixed in the latest release.  I'm at the mercy of how the system sends that information and PF2E only sends the filename.  So the sorting should be consistent now, but not entirely sorted properly.
