### ISSUE TITLE
[PF2e] "Cannot read properties of undefined (reading 'token-highlight')"

### ISSUE THREAD

**Issue by jocolamarco** [ironmonk88/monks-little-details#165]
Error message logged when I refreshed tokens and not in combat:

![image](https://user-images.githubusercontent.com/45291719/164015065-6f190e5e-9bd1-4c2b-9aec-db3ac27c5cab.png)

**Comment by jocolamarco** [comment]
![image](https://user-images.githubusercontent.com/45291719/164015494-9db200b8-7208-464b-87de-0861df5256a9.png)

**Comment by galaara98** [comment]
im getting this also, when ever i open a tokens config
foundry.js:319 
        
       TypeError: Cannot read properties of undefined (reading 'token-highlight')
[Detected 1 package: monks-little-details]
    at combat-marker.js:112:86
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at TokenConfigPF2e._render (foundry.js:3117:13)
    at async TokenConfigPF2e._render (foundry.js:3764:5)

Foundry 9.269 Stable
PF2E 3.8.4.11118
Monks little details 1.0.47

**Comment by vt-tom** [comment]
I got the same in die DnD System:
Foundry 9.269 Stable
DnD 1.5.7
Monks little Details 1.0.47

![grafik](https://user-images.githubusercontent.com/80099175/165380198-bd94d7e9-11b4-413a-84ea-9556183dce5f.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
