### ISSUE TITLE
(BUG) Right clicking on actor does nothing for player

### ISSUE THREAD

**Issue by uniwars** [ironmonk88/monks-little-details#166]
Hi, it seems that the last update of monk's little details broke up some things leading to players who can't right click an actor in the actor directory

When right clicking an actor players gett his error 👍 
![image](https://user-images.githubusercontent.com/65986545/166157798-b03f9857-582c-456d-92cd-20c3c7f8e997.png)
and then nothing happens

GM can still right click and see the menu

Last Foundry version, pf2e system on last version

**Comment by uniwars** [comment]
I deactivated force client setting, the problem is still present
I also tested and only owned actor are concerned

**Comment by ironmonk88** [comment]
This should be fixed now.
