### ISSUE TITLE
Background pallete does not work

### ISSUE THREAD

**Issue by cs96and** [ironmonk88/monks-little-details#17]
I've tried several different browsers and also tried disabling all modules apart from Monk's Little Details, but cannot get the background palette function to work.  No colours are displayed to choose from. E.g....

![image](https://user-images.githubusercontent.com/898086/109159361-6df6db80-776c-11eb-8448-461b4bb864aa.png)

I see this error in the console...

![image](https://user-images.githubusercontent.com/898086/109159803-f5444f00-776c-11eb-9c1c-8e49316e9651.png)

**Comment by ironmonk88** [comment]
It's a bit of a known bug.  I'm guessing you're on the Forge?  Or the image you're trying to use is hosted on a different site.
I looked into it but couldn't find a decent solution.
Leaving this open to remind myself to look into it again.

**Comment by cs96and** [comment]
Yes the background image is hosted in an S3 bucket

**Comment by ironmonk88** [comment]
I made a couple changes with the latest version.  It might have helped.

**Comment by ironmonk88** [comment]
1.0.15 changed the way I process the images.  Can you let me know if this is still an issue?

**Comment by ironmonk88** [comment]
Closing the ticket.
