### ISSUE TITLE
Tile Browser tool drag & drop doesn't work

### ISSUE THREAD

**Issue by MadDave123** [ironmonk88/monks-little-details#171]
**Issue**:
Images dragged from the Tile Browser tool window onto the canvas disappear immediately.

**Reproduction**:
- Click on Tile Browser tool.
- Navigate to any folder with image assets.
- Drag an image from the Tile Browser window onto the current canvas.
- The tile image will fail to appear on the canvas

**Notes**:
- Tested on a new world with no other modules active.
- Adding images via the Place Tile tool works as expected.
- Foundry v9.239
- Module v1.0.49

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
