### ISSUE TITLE
Error: Mod Conflict 

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#174]
[W] libWrapper: Potential conflict detected between module Damage Log and [module Actually Private Rolls, module Monk's Little Details].
Module damage-log did not chain the wrapper for 'ChatLog.prototype.notify'. libWrapper-notifications.js:89:5

https://gitlab.com/koboldworks/agnostic/private-rolls
https://github.com/cs96and/FoundryVTT-damage-log

I'll sign up for GitLab & open a ticket there too. Not really sure who has the issue here.

**Comment by ironmonk88** [comment]
I think that would be a damage log issue.
Double-checked and the notify code looks properly wrapped on my end.

**Comment by cs96and** [comment]
Damage log already ignored the conflict in `ChatLog.prototype.notify` for Monk's Little Details.  I've now also ignoring conflicts with Actually Private Rolls too.
https://github.com/cs96and/FoundryVTT-damage-log/issues/17
