### ISSUE TITLE
Bug: Character Sound Effects

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#176]
Not working on Forge; it is still working on stand-alone Foundry.

GET(sound filepath here)
[HTTP/2 404 Not Found 580ms]

Foundry VTT | Failed to load audio node: 
error { target: audio, isTrusted: true, srcElement: audio, currentTarget: audio, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
foundry.js:63423:15

HTTP load failed with status 404. Load of media resource (sound filepath here) failed. game

**Comment by ironmonk88** [comment]
Should be added to the latest version.
