### ISSUE TITLE
Feature Request: Option to prevent start of encounter if initiative hasn't been rolled yet

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#178]
**No Combat Without Initiative** tiny helper option. 

When Staring an Encounter, if any actor in the combat tracker has not rolled the initiative yet, show a warning message and do not start the Combat Encounter. This saves DM from starting encounters where the first actor may not be the first because he forgot to roll initiative for some actors, such as the monsters.

**Comment by ironmonk88** [comment]
Should be added to the latest version.

**Comment by apoapostolov** [comment]
Thank you very much for implementing this.
