### ISSUE TITLE
Feature Request: Hide NPCs from Combat Tracker until their turn

### ISSUE THREAD

**Issue by ckdragons** [ironmonk88/monks-little-details#179]
As it is now, the players will see all combatants in the Tracker when combat starts, even those that out of line of sight. I'm already using the option to hide initiatives until their turn. I'd like to have an option that would hide any NPC that hasn't acted yet without having to go to each NPC and set their token to hidden.

For example, there is a goblin in the doorway facing the PCs. What the PCs don't see behind that goblin is his 10 friends waiting around the corner. I'd like it where those extra goblins don't appear to the PCs in the Combat Tracker until their turn in the first round.

**Comment by ironmonk88** [comment]
Should be added to the latest version.
