### ISSUE TITLE
Altered Status Effects for PF2

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#18]
I am aware that this mod is particularly made for 5E but a lot of its functionality (especially related to combat tracker) are useful for other systems as well. As such, I would kindly ask for one more feature to be made usable by PF2 in particular.

The Altered Status Effect CSS is amazing in my 5E games and would like to have a similar thing in my PF2 games as well. Being able to see the texts of the conditions without having to mouse over above each is a must for me. 

I want to turn this:

![image](https://user-images.githubusercontent.com/4083812/109429821-c5b07380-7a06-11eb-8f4a-bb4ed7424b7d.png)

...into this:

![image](https://user-images.githubusercontent.com/4083812/109412551-5492a100-79b1-11eb-938b-57b838cfaaab.png)

**Comment by ironmonk88** [comment]
Status effects can now be shown for pathfinder.  Although it might change the colour of the icons.  I'll work on providing a way to work around that.

**Comment by ironmonk88** [comment]
Setting has been added to prevent the colour from being changed on icons.
