### ISSUE TITLE
Feature Request: scale token highlight with token scale

### ISSUE THREAD

**Issue by bobrien87** [ironmonk88/monks-little-details#183]
### Request
Scale token highlight image or animation relative to the scale of the token.

### Screenshots

- [x] Scenario 1: highlight animation is scaled to 2, token is scaled to 1 - animation sits behind token perfectly 
![Screenshot 2022-06-27 234445](https://user-images.githubusercontent.com/35534676/176048991-395ec7ac-c125-43c2-a8dd-b172708c7010.jpg)
- [ ] Scenario 2: highlight animation is scaled to 2, token is scaled to 0.8 - animation surrounds token instead of bordering it
![Screenshot 2022-06-27 233951](https://user-images.githubusercontent.com/35534676/176048630-d3109a65-ece2-4244-b407-2f8f7ffe8e49.jpg)

**Comment by ironmonk88** [comment]
Fixed in latest release
