### ISSUE TITLE
Bug: Combat Highlight Image

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#185]
The Combat Highlight Image filepath doesn't save when setting it on an actor's Prototype Token. It saves on already placed tokens.

Foundry 9.269
D&D 5e 1.3.2
LD 1.0.55
FTC ✔️

**Comment by ironmonk88** [comment]
This should be fixed in v10.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release
