### ISSUE TITLE
3.5e SRD system incompatibility

### ISSUE THREAD

**Issue by ilore** [ironmonk88/monks-little-details#186]
I have been using this incredible module with 3.5e SRD system for a long time. Although there are some incompatibilities (you must deactivate the Css option) the rest of the module's features has been working fine until now:

After the new system 3.5e update, when you create an encounter, player's can't see it. I have been talking with the system creator, but he doesn't know why this module has stopped working.

When I create a combat encounter as Game Master, players receive this console error message: 

![Console-error-message](https://user-images.githubusercontent.com/32924279/186717900-5a154c90-0bfc-4971-9846-1edeed9d169a.jpg)

It would be great if you could make this module compatible with 3.5e SRD system again.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release

**Comment by ilore** [comment]
The problem continues happening. The module works just fine in the Game Master account. However, players can't see the active combat in the combat tab. Player's console shows this error message when the GM creates a combat:

![Player-console-error](https://user-images.githubusercontent.com/32924279/199281520-0bb6b6d1-07f2-4a79-88e7-4065743e1a43.jpg)

A detail that maybe could help:  3.5e SRD system was created using Pathfinder 1 system. However, the 3.5e SRD creator has changed lots of things.
