### ISSUE TITLE
Dragging image from FilePicker to Canvas error in v10

### ISSUE THREAD

**Issue by Freeze021** [ironmonk88/monks-little-details#188]
With Monks Little Details active dragging an image from the FilePicker to the canvas errors out.

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'x')
[Detected 1 package: monks-little-details]
    at TilesLayer.onDropData (monks-little-details.js:311:73)

Hope the attached error message helps.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release
