### ISSUE TITLE
Invisible Man instead of Mystery Man - not available for PF2

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#19]
Since this is just an icon swap, I wonder why it is not marked available for PF2, can we please have this option?

**Comment by ironmonk88** [comment]
I just didn't think PF2 players would want it as it's a DnD icon.  Guess that's not really a reason to remove it.  :-)
I've updated the code, the Invisible Man of Mystery will show up with the next release.

**Comment by ironmonk88** [comment]
1.0.15 just released and should provide that option.
