### ISSUE TITLE
Feature Request - adjusted formatting of Combat Round Message

### ISSUE THREAD

**Issue by Gurrgel** [ironmonk88/monks-little-details#191]
A very minor issue / feature request, but the Combat Round message is currently not quite aligned with other chat messages, the trash can is aligned slighty further to the right compared to other chat messages, and the line height of the message seems to be a few pixels lower compared to the header line of other messages.

This makes it slightly harder to delete chat messages, since you can deleate 100+ regular chat messages without moving your mouse button (since the trash can to delete it remains in the same place as each message is removed), whereas you manually have to move the cursor whenever you get to a new round message.

See more details here: [https://discord.com/channels/862414864692281386/862421146276200478/1016312999583158272]
![image](https://user-images.githubusercontent.com/99760890/188482808-b5438238-a17c-4b1c-ad2a-4b3293b88cb8.png)

**Comment by ironmonk88** [comment]
This should be fixed in the latest release
