### ISSUE TITLE
[BUG] Dropping tiles from the tile browser throws fault

### ISSUE THREAD

**Issue by UnoriginalDM** [ironmonk88/monks-little-details#192]
Monk's Little Details ver: 1.0.58
FoundryVtt ver: 10.284
DND 5e ver: 2.0.2

No other modules activated (besides libWrapper).

Steps to recreate:
1. Open Tile Browser
![image](https://user-images.githubusercontent.com/77896718/189348375-d82eaa9d-ec6d-4c47-a408-479c72f4029b.png)
2. Try to drop a tile on the canvas
![image](https://user-images.githubusercontent.com/77896718/189348476-f5972109-e0c3-4b2c-a1b1-c2dfc03e296f.png)

**Comment by ironmonk88** [comment]
This should be fixed in the latest release
