### ISSUE TITLE
[BUG] Text not showing on status icons when in PF2E system

### ISSUE THREAD

**Issue by srcarpet** [ironmonk88/monks-little-details#195]
**Describe the bug**
Text not showing on status effects selector when in PF2E system

**To Reproduce**
1. Create PF2E world
2. Enable module
3. Check status effects

**Expected behavior**
Text displaying status effects

**Screenshots**
![image](https://user-images.githubusercontent.com/65621024/190209996-b9d2ef8b-1863-4700-9b57-a5c89ebf91eb.png)

**Please complete as much of the following information as possible:**
 - Browser: Firefox
 - Foundry Version v10
 - System: Pathfinder 2e]
 - Module version 10.1

**Additional context**
Was not happening in v9

**Comment by ironmonk88** [comment]
This should be fixed in the latest release
