### ISSUE TITLE
[BUG] v10. Challenge Rating Tracker

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#196]
The challenge rating tracker is missing in v10.
### V9
![image](https://user-images.githubusercontent.com/99844555/190238026-97d3bc5c-b854-4b64-841e-028cdf9301ce.png)
### V10
![image](https://user-images.githubusercontent.com/99844555/190238143-e7c787ce-3452-4cf2-844b-5d881cd860c0.png)
![image](https://user-images.githubusercontent.com/99844555/190238253-00b6728a-5cbc-4059-a660-e33248852e0d.png)

Little Details 10.1
Only mods active are yours.
![image](https://user-images.githubusercontent.com/99844555/190238330-40a74245-be0a-43ed-93ec-bce93c4fc5fe.png)

**Comment by Rubengam3r** [comment]
I am experiencing the same results as the original issuer. I'm looking for any console errors and not seeing them.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release
