### ISSUE TITLE
PF2, Conditions with Names broken due to CSS change

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#199]
The font of the condition names is now fully black.

![image](https://user-images.githubusercontent.com/4083812/191272628-9e5f67bb-abbd-4ca8-ab77-6c253eb7fe39.png)

**Comment by ironmonk88** [comment]
Duplicate of #195

**Comment by ironmonk88** [comment]
This should be fixed in the latest release
