### ISSUE TITLE
[Minor Bug] CR Rating in Combat Tracker disapears when Vehicle Actor is present

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-little-details#2]
When using the "Next Up" Modulle - the CR Rating isn't displayed, probably because the Vehicle Actor has no CR Rating:

![image](https://user-images.githubusercontent.com/44159008/105769998-f4967e00-5f5e-11eb-9b67-a280a5b3b57e.png)

![image](https://user-images.githubusercontent.com/44159008/105770220-33c4cf00-5f5f-11eb-98fb-446d60993230.png)

(Awesome module!! <3)

**Comment by ironmonk88** [comment]
Good catch, totally due to not having an xp value.
Code has been fixed and will show properly in the next patch.

**Comment by ironmonk88** [comment]
Should be fixed with 1.0.5
