### ISSUE TITLE
Options should force a reload

### ISSUE THREAD

**Issue by mclemente** [ironmonk88/monks-little-details#20]
When changing the `Add DnD Statuses` and `Use DnD5e invisible icon` they don't change the HUD, requiring a reload.
To do that, add the following to the settings

```javascript
onChange: () => {
  location.reload();
 }
```
Some other options might need it as well, but those two are the only ones noticed.

**Comment by ironmonk88** [comment]
Thank you, that's awesome.  One of those, didn't know it existed, or that I needed it, until now.
I'll go through the other settings to see if anything stands out, and update my other modules when I get a chance.

**Comment by ironmonk88** [comment]
Updates have been added to 1.0.15.  Thank you again for the tip.
