### ISSUE TITLE
[BUG] Auto-Scroll Combat Tracker

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#200]
Doesn't scroll, despite the settting being active. Tested on v9 & v10.

https://user-images.githubusercontent.com/99844555/191619694-3fcd07c4-dfa2-463a-b51e-93f1a9b14eb9.mp4

Little Details 1.0.55 & 10.1

**Comment by ironmonk88** [comment]
![KeepAtTop](https://user-images.githubusercontent.com/75920956/191654431-293e9b98-6613-4d66-9754-7caad542a414.gif)
Working as expected for me.
It just scrolls the scroll bar so the token is at the top... it doesn't re-order the icons.
So if you don't have enough tokens to have a scroll bar, you aren't going to see any difference.
