### ISSUE TITLE
PF2, fixed Conditions very unreadable, esp. when zoomed out

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#201]
![image](https://user-images.githubusercontent.com/4083812/191673969-b6ad6ec2-4106-49ce-8083-e272f1f1e766.png)

Thanks for fixing the condition titles, but they are very dark and very hard to read. Raising the readability color to white or very light grey rather than mid-grey or dark-grey as now would greatly improve readability. 

Tested with Culprit, no Dorako UI or other CSS conflict.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
