### ISSUE TITLE
[Feature Request] Remove defeated tokens from combat

### ISSUE THREAD

**Issue by cstby** [ironmonk88/monks-little-details#203]
**Is your feature request related to a problem? Please describe.**
When running combat as a GM, I must manually remove defeated tokens from combat. Alternatively, I can skip them by ending their turn right away each time they come around.

**Describe the solution you'd like**
When a token is marked defeated/dead, remove it from combat.

**Additional context**
In my context, deleting the token from the canvas would be fine.

**Comment by cstby** [comment]
Turns out that core foundry includes a setting (in the combat tracker) to skip tokens marked defeated. Maybe this enhancement isn't needed.

**Comment by ironmonk88** [comment]
Should be available in the latest version
