### ISSUE TITLE
[BUG] Use keys to swap tools

### ISSUE THREAD

**Issue by roguedevjake** [ironmonk88/monks-little-details#204]
**Describe the bug**
Foundry throwing up error and hotkeys not working correctly

**To Reproduce**
1. Enable "Use keys to swap tools"
2. Open console
3. Select a tool other than the token layer
4. Push G or Select G

**Expected behavior**
It will quick show or move to the token layer (or whatever other layer)

**Please complete as much of the following information as possible:**
 - Foundry Electron
 - Foundry Version 10.286
 - System D&D5e 2.0.3
 - Module version 10.2

**Additional context**

No other modules are enabled

```
Uncaught TypeError: Cannot set property activeControl of #<SceneControls> which has only a getter
    at MonksLittleDetails.swapTool (monks-little-details.js:465:43)
    at Object.onDown (monks-little-details.js:452:56)
    at KeyboardManager._executeKeybind (foundry.js:2147:66)
    at KeyboardManager._processKeyboardContext (foundry.js:2186:33)
    at KeyboardManager._handleKeyboardEvent (foundry.js:2224:10)
    at foundry.js:1873:54
swapTool @ monks-little-details.js:465
onDown @ monks-little-details.js:452
_executeKeybind @ foundry.js:2147
_processKeyboardContext @ foundry.js:2186
_handleKeyboardEvent @ foundry.js:2224
(anonymous) @ foundry.js:1873
```

**Comment by DariusWolfe** [comment]
I am having this problem as well.
Foundry Electron
FVTT Version 10, build 286
System: PF2E version 4.2.3
Module version: 10.2

**Comment by esheyw** [comment]
Can confirm this is still a thing, 10.288, pf2e 4.2.6, module 10.3

**Comment by ironmonk88** [comment]
Should be fixed in the latest version

**Comment by DariusWolfe** [comment]
Seems to be! Noticed it this morning while doing some prep to finally move the campaign to v10. It's muscle memory at this point to use the hotkeys, so it took me a moment to realize that it was now working in v10.
