### ISSUE TITLE
PF2, the wide conditions panel doesn't support the new PF2 condition Undetected

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#205]
The wide panel for conditions with condition names does not have recognition for PF2 new condition Undetected. While it works when clicked, it doesn't mark as active like other conditions.

![image](https://user-images.githubusercontent.com/4083812/194185382-6aec861d-16b4-4039-9eae-ce327285587f.png)

**Comment by ironmonk88** [comment]
This actually looks like a PF2E issue.  With Little Details turned off, the status still doesn't show as active.
MLD really just responds to what the system says is active.
I havn't investigated further to see what's happening that PF2E isn't activating that button.

**Comment by ironmonk88** [comment]
Closing this as there's not much I can do.
PF2E has listed `undetected` as not in the HUD.  But it is.
Once they fix that it should work correctly.

**Comment by apoapostolov** [comment]
Sure, thanks for checking the issue.
