### ISSUE TITLE
[Bug] Creature sound preview dont show anymore after 10.287 in Warhammer system 

### ISSUE THREAD

**Issue by danil0man** [ironmonk88/monks-little-details#207]
**Describe the bug**
Creature sound preview dont show anymore after 10.287 in Warhammer system

**To Reproduce**
Open the character sheet and there is no sound icon anymore.

**Expected behavior**
It was working in version 20.286 together with the Warhammer system

**Screenshots**
![image](https://user-images.githubusercontent.com/72052103/194704928-485e2324-cbfc-486a-a4c0-71568f9d8c98.png)

**Please complete as much of the following information as possible:**
 - Browser Brave (Chromium)
 - Foundry Version 10.287
 - System Warhammer Fantasy 4th Edition
 - Module version 6.1.4
 - Are there any errors in the console The only I can see is this
![image](https://user-images.githubusercontent.com/72052103/194704982-1680399d-a6a7-48a3-86b3-bcf43043cad9.png)
 - Have you tried using `Find the Culprit` to ensure it isn't a module interaction?
 Yes. is pointing to monks little details, but it was working just yesterday

**Additional context**

**Comment by Crowguard** [comment]
![image](https://user-images.githubusercontent.com/99844555/194716929-c777b19b-ff0e-44f0-9970-f36968f937e1.png)
Update: it is there on NPC types. All the other actor types are missing it.

**Comment by ironmonk88** [comment]
Have you changed the settings to include all charater types?

**Comment by Crowguard** [comment]
I did after seeing the Discord message; they all show up once the setting is on "All".

**Comment by danil0man** [comment]
Yes, the issue is resolved wit the setting change

**Comment by ironmonk88** [comment]
Closing because the issue has been resolved.
