### ISSUE TITLE
XP is not working

### ISSUE THREAD

**Issue by belkasro** [ironmonk88/monks-little-details#209]
im hosting  pathfinder 2e game version 10 patch 5 288 build and pathfinder 2e version 4.2.6.  

when you end combat it use to give xp but not it gives NAN in the xp box now. was there a change or anyone else running into this issue. Ive tried to look up the code with f12 and its not showing up anything when it begins, during or ends.

**Comment by ironmonk88** [comment]
Yep, PF2E made a change, I just havn't caught up to fixing it yet.

**Comment by belkasro** [comment]
OK

**Comment by ironmonk88** [comment]
Fixed in latest release
