### ISSUE TITLE
[BUG] Combatants being incorrectly set as not defeated

### ISSUE THREAD

**Issue by colinbate** [ironmonk88/monks-little-details#210]
**Describe the bug**
If you close an NPC sheet after that NPC has been marked as defeated, it will be set as not defeated.

**To Reproduce**
1. Run a clean copy of Foundry and install Monk's Little Details
2. Create or import a PC and NPC and add them to the default scene
3. Start combat with them
4. Reduce the NPC to zero HP (it should be set as defeated)
5. Open that NPC's sheet
6. Close the sheet

**Expected behavior**
Nothing should happen when you close the sheet. Instead, the combatant in question is set as not defeated.

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version: v10.288 (I think v9 as well)
 - System: dnd5e (an issue with this system is causing this, but may affect others)
 - Module version: 10.2
 - Are there any errors in the console: no
 - Have you tried using `Find the Culprit`: N/A as only have one module installed

**Additional context**
Brought up in Discord. Have a PR ready.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
