### ISSUE TITLE
[BUG] 3.5e SRD system incompatibility. Players can't see the active combat.

### ISSUE THREAD

**Issue by ilore** [ironmonk88/monks-little-details#215]
This bug was supposedly repaired in one of the last patches, but it is still happening.

When the Game Master creates an encounter, players can't see it. I have been talking with the 3.5e SRD system creator, but he doesn't know why this module has stopped working.

![two-screens](https://user-images.githubusercontent.com/32924279/199288979-e8ce06de-93a0-4e97-8a4a-ede52b9d9288.jpg)

When I create a combat encounter as Game Master, players receive this console error message:

![Player-console-error](https://user-images.githubusercontent.com/32924279/199284368-71422f1f-d3ca-4350-a6e6-ced702fca250.jpg)

The GM console doesn't show any error message. In fact, for the GM, the module works just fine.

I'm using FVTT V 10 Compilation 288 and 3.5e SRD system version 2.0.4

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
