### ISSUE TITLE
PF2e Token highlight in combat visible for undetected token

### ISSUE THREAD

**Issue by uniwars** [ironmonk88/monks-little-details#216]
**Is your feature request related to a problem? Please describe.**
The PF2e system added a rules-based vision that handle the visibility for a PC of another token via sight, earing, thermosens, scent, etc. The highlight of a token during its turn is visible for everyone even if the token is not, giving its position and movement.

**Describe the solution you'd like**
I have no idea how it could be fixed, but maybe check if the token is visible for a PC and don't show the animation for that PC if it isn't

**Additional context**
![image](https://user-images.githubusercontent.com/65986545/199577638-41002dba-2454-4776-bb33-5d430106eda4.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
