### ISSUE TITLE
[BUG] Token Highlight rendering beneath background tiles

### ISSUE THREAD

**Issue by EarlyWhirly** [ironmonk88/monks-little-details#217]
**Describe the bug**
The combat token highlight is rendering beneath background tiles in Foundry V10

**Screenshots**
![image](https://user-images.githubusercontent.com/117322663/199624174-9c866cc0-0a17-4c9b-95ec-bcb7e0bcbd93.png)

 - Browser - Tested in Foundry app and Chrome
 - Foundry Version - v10.288
 - System - D&D5e, Pathfinder 2e
 - Module version - v10.3
 - No Errors in console
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction - N/A, Tested on clean world, No other modules.

**Additional context**
Setting the Z-Index of the tile to a negative integer renders the marker above the tile

**Comment by ChobitsCrazy** [comment]
Came to report this issue as well, just as an FYI this also affects the bloodsplat for dead enemies.

**Comment by YenBenGrey** [comment]
I have been given this link because it is happening to me too.

Large tile across my scene, can't see any token marker, take the token outside the confines of the tile and you can see the token marker.

**Comment by Kelmey** [comment]
Can confirm this is happening in my game as well.  MLD v10.4 Foundry 10.291 and dnd5e 2.0.3 system

**Comment by ironmonk88** [comment]
Fixed in latest release
