### ISSUE TITLE
Pf2e CR calculation shows wrong result

### ISSUE THREAD

**Issue by DawidIzydor** [ironmonk88/monks-little-details#218]
**Describe the bug**
Pf2e CR calculation shows the encounter to be much harder than it is

**To Reproduce**
Create an encounter with one level 3 monster and four level 4 creatures. The encounter is marked as extreme

**Expected behavior**
The encounter to be marked as trival level (1 creature 1 level below average party level, as here: https://2e.aonprd.com/Rules.aspx?ID=497 )

**Comment by DawidIzydor** [comment]
looks like the disposition of a player token is by default set to -1 and the calculation logic relies on this to be 1

**Comment by DawidIzydor** [comment]
After further research, the whole disposition field is removed from the Pf2e actor https://github.com/foundryvtt/pf2e/blob/2a69b980732c29ff86d7ac6287077551a21863fe/src/module/collection/actors.ts#L8

**Comment by ironmonk88** [comment]
Well... there's not much I can do without the disposition flag.
I'm not entirely sure where PF2E is going with that, but that really throws a wrench into a bunch of plans.

**Comment by DawidIzydor** [comment]
I suggest to have this setting hidden and disabled from Pf2e as it's currently fully broken, it works/shows the correct CR only in very specific scenarios, and show very different values in the vast majority of cases

**Comment by ironmonk88** [comment]
So, you can set the character sheet to the default version rather than the pf2e version and get access to the disposition flag.
Technically speaking... the function is working exactly as it should, it's just PF2E that makes it difficult to tell why it's not working correctly.  And there is a setting to turn it off.  I'll set the default setting to off for PF2E.  And hopefully they turn the disposition flag back on.

**Comment by ironmonk88** [comment]
Closing this as there's not much I can do, and there is a workaround.

**Comment by rmressler** [comment]
The disposition seems to be working for me just fine, it's actually the math that seems to be not quite right. I'll put in a pull request with my updates, it is working for me now on the latest PF2e system build.
