### ISSUE TITLE
[BUG] Graphical glitch in menu titles

### ISSUE THREAD

**Issue by yjeroen** [ironmonk88/monks-little-details#220]
**Describe the bug**
You see a dark grey bar in the titles of menu windows.

![image](https://user-images.githubusercontent.com/1303988/200180057-f452e586-608c-4ccd-99bb-52d94bc84dba.png)

**To Reproduce**
1. Start a Forbidden Lands system world.
2. Enable Monk's Little Details

**Expected behavior**
No grey bar when Monk's Little Details is disabled.
![image](https://user-images.githubusercontent.com/1303988/200180133-044cf0ac-bb65-4a36-b52c-53a2572a6828.png)

**Screenshots**
See above.

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version v10.288
 - System Forbidden Lands 10.0.0
 - Module version 10.3
 - Are there any errors in the console [e.g. press F12 and look for red text] No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Yes

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
