### ISSUE TITLE
[BUG] Deprecated warning wrong way around?

### ISSUE THREAD

**Issue by itteerde** [ironmonk88/monks-little-details#222]
**Describe the bug**
Warns about deprecation the wrong way around maybe?

**To Reproduce**
1. Execute (I think perfectly fine Macro on Wildcard Token)
2. Check F12

```
// https://github.com/krbz999/zhell-macros/blob/main/tools/token/cycle_token_wildcards.js
const currentImg = token.document.texture.src;
const actorId = token.actor.id;
const wildcardImages = await game.actors.get(actorId).getTokenImages();
const currentIndex = wildcardImages.indexOf(currentImg);
const next = (currentIndex + 1) === wildcardImages.length ? 0 : currentIndex + 1;
await token.document.update({ "texture.src": wildcardImages[next] });
```
![image](https://user-images.githubusercontent.com/8367477/201538604-d31ea90f-5ab0-4905-bcc4-ed7ce674ae7e.png)

https://discord.com/channels/170995199584108546/699750150674972743/1041418781903294534

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
