### ISSUE TITLE
[BUG] No "Find My Token" button?

### ISSUE THREAD

**Issue by dcoughler** [ironmonk88/monks-little-details#223]
**Describe the bug**
I've enabled the "Find My Token" setting, but for the life of me I cannot find the "Find My Token" button. Where is it supposed to be and is it only for players? It is not mentioned in the documentation either (unless I am totally blind).

Monk's Little Details 1.0.55 on Foundry v9.269.

**Comment by ironmonk88** [comment]
Find My Token is only available for players.  Since every token is considered owned by the GM... there's no real point in trying to find a token for the GM as it will just end up cycling through all of them.

**Comment by dcoughler** [comment]
May I change this to a feature request then? For GMs in the Combat Tracker,
and "Find My Token" option might be good, depending on the functionality.
I'll have to have a look as a player.

**Comment by ironmonk88** [comment]
If you click on the combatant's icon in the combat tracker it will automatically pan to that token.
That's core Foundry functionality.

Find My Token might be useful for GMs if they want to cycle through all tokens on the scene though.  I could hide it behind a setting.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
