### ISSUE TITLE
[BUG] Can't drag/drop combatants on Popout Combat Dialog

### ISSUE THREAD

**Issue by ckdragons** [ironmonk88/monks-little-details#226]
**Describe the bug**
I'm not able to drag the combatants to rearrange them in the popout combat dialog. I'm able to do this in the Combat tab. 

**To Reproduce**
1. Add combatants to a combat
2. Roll initiatives
3. Start combat to open the combat dialog
4. Can't drag combatants to different positions to rearrange combat order

 - Firefox 106.0.5
 - Foundry Version v10.290
 - Pathfinder 1e 82.2

**Comment by ironmonk88** [comment]
I can re-order in the Combat Popout.
Please run Find the Culprit to make sure it's Monk's Little Details causing the issue.

**Comment by ckdragons** [comment]
Determined the issue was a fault with another module (Combat Enhancements). Appreciate the response.
