### ISSUE TITLE
[BUG] Compendium Folders & scenes with no background

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#227]
Scenes with no background image in compendiums don't display properly in scenes containing Compendium Folders, even if CF is deactivated.

1. Activate Compendium Folders module
2. Make a new scene compendium.
3. Drag a blank scene into it. Scene should be visible
4. Make a compendium folder inside it. Scene should just be a thin line/disappear.
5. Deactivate MLD; compendium should look like the second pic.

### Just MLD active, in a compendium that contains Compendium Folders data.

![image](https://user-images.githubusercontent.com/99844555/205219375-8e399cf1-9597-4707-a22f-2b5102d515b1.png)

### MLD + Compendium Folders active

![image](https://user-images.githubusercontent.com/99844555/205219652-7ab9b4f3-b9cb-4508-b2c6-d6b595fda4d6.png)

### Info
MLD 10.4
Compendium Folders 2.5.5

**Comment by ironmonk88** [comment]
Fixed in latest release
