### ISSUE TITLE
[BUG] turn animations art gets stuck after combat ends.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [ironmonk88/monks-little-details#228]
turn animation gets stuck after combat has ended.

**To Reproduce**
1. start combat 
2. end combat
3. see the animation isnt working and the art has been stuck to the token it was last on.

**Expected behavior**
a usual use of turn animations and for it to be removed at end of combat

**Screenshots**
![image](https://user-images.githubusercontent.com/62528192/205431718-8f28d7b0-4fd6-4c35-8f21-0f6b25729c45.png)

**Please complete as much of the following information as possible:**
 - firefox
 - Foundry Version 10 build 291
 - System pathfinder 2e
 - Module version 10.4
 - Are there any errors in the console 
![image](https://user-images.githubusercontent.com/62528192/205431782-b2039bf0-912d-4559-b470-e5447ad6b7be.png)

**Additional context**

**Comment by ironmonk88** [comment]
Can you run Find the Culprit?
I can't replicate the issue, and I suspect there's another module causing issues.
The error message posted looks like it's from a different module.

**Comment by ThingsCouldGetDicey** [comment]
i think its resolved now as this was a while ago.

**Comment by ironmonk88** [comment]
Closing this as it seems to be resolved?
