### ISSUE TITLE
[BUG] Players can set and use hotkeys to access GM layers

### ISSUE THREAD

**Issue by Kelmey** [ironmonk88/monks-little-details#229]
**Describe the bug**
Players have the ability to use the "Configure Control" section to change all of this modules hotkeys. Some, like the lighting layer hotkey is set by default. 

They can then use those hotkeys to switch to the layers and see things like lighting, walls, etc. 

Luckily it seems that players can't modify walls, lights, etc. But the ability to view the layers is a problem. =)

**To Reproduce**
1. With default controls the can just press 'J' or 'SHIFT + J" to view lights.
2. They can open configure controls and set any hotkey from Monk's Little Details, then use them to access all layers

**Expected behavior**
I would expect players to only be able to use the hotkeys for the token, measure, drawing, and journal layers since they can normally use those layers. 

**Screenshots**
[Player viewing the wall layer.](https://drive.google.com/file/d/1fqG8FlCW82wmEw5Xkw0-CXmcsRVvQQEF/view?usp=sharing)

**Please complete as much of the following information as possible:**
 - I used latest Chrome version, Player who reported to me was using Edge.
 - v10.291
 - dnd5e 2.0.3
 - MLD version 10.4
 - Only errors I saw are when player tries to place walls.

**Comment by Kelmey** [comment]
I have verified this still happens on a new game world with only this module enabled.

You do have to check "Use keys to swap tools" in settings which enables the ability to use and set the hotkeys. Which is good since I can disable this until fixed. =)

**Comment by ironmonk88** [comment]
Fixed in latest release
