### ISSUE TITLE
[BUG] Dead Token Opacity

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#232]
Token's opacity is being reduced regardless of these two settings when they're marked defeated. 
![image](https://user-images.githubusercontent.com/99844555/209757877-75dd8d4a-0b9c-47fa-9ca0-e912b0d7be87.png)
Not entirely sure how; they aren't being hidden or having their actual token opacity bar adjusted.
![image](https://user-images.githubusercontent.com/99844555/209758263-ba0b5ef5-8cc1-4477-979f-6f7f4243601e.png)

https://user-images.githubusercontent.com/99844555/209757777-1da8ea36-16d7-4a49-a385-0d4143fb3275.mp4

Little Details 10.4
Foundry 10.291
D&D 5e 2.0.3
FTC ✔️ (I left Always HP on)

**Comment by ironmonk88** [comment]
That looks expected.
When bloodsplats happen, the token transparency is ignored.
Instead this setting is used.
![image](https://user-images.githubusercontent.com/75920956/210035449-7f17a14c-fbfd-431a-8dd9-0063d8e8c97a.png)

**Comment by Crowguard** [comment]
Yep, that was it; sorry about this ticket. Thanks.
