### ISSUE TITLE
[BUG] Challenge Rating Doubles

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#234]
Adding a token to the combat tracker while the mini-tracker is popped out results in the CR showing up twice.

![image](https://user-images.githubusercontent.com/99844555/210919035-34f20e67-7cb5-470c-bb7b-bae581d0ae60.png)

https://user-images.githubusercontent.com/99844555/210919006-03724506-a268-43f2-b12c-05b4d8ee529d.mp4

Edit: Right-clicking the combat tab to pop it out keeps adding this until it extends off the bottom of the screen.

https://user-images.githubusercontent.com/99844555/210919710-5a7ca8ac-d43d-4c18-88e2-3277c3ab2000.mp4

Foundry 10.291
D&D 5e 2.0.3
Little Details 10.5
FTC ✔️

**Comment by ironmonk88** [comment]
Should be fixed in the most recent release.
