### ISSUE TITLE
[BUG] Bloodsplats visible over the fog of war

### ISSUE THREAD

**Issue by Wolfinton** [ironmonk88/monks-little-details#237]
**Describe the bug**
Bloodsplats are visible over the fog of war, meaning that players can see that there are corpses in areas before they visit them (and after they have visited, left, and no longer have vision).

**To Reproduce**
Enable bloodsplats. Create walls / fog of wall.

**Expected behavior**
Bloodsplats should not be visible over the fog of war (and this used to be the case).

**Screenshots**
![image](https://user-images.githubusercontent.com/113951696/211399813-773eb402-e703-4ffd-819f-66ede435790f.png)

**Please complete as much of the following information as possible:**
 - Foundry Version v10 build 291
 - System Pathfinder 2e
 - Module version v10.5

**Comment by Crowguard** [comment]
Can confirm its also in D&D 5e 2.0.3

![image](https://user-images.githubusercontent.com/99844555/212457312-864e258c-d0e0-4345-8432-e9dfa3dc6173.png)

**Comment by ironmonk88** [comment]
Should be fixed in the most recent release.
