### ISSUE TITLE
Minor Issue with PF2 Named Conditions option

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#24]
First, thank you very much for making it work with PF2. It looks amazing and the conditions are finally easy to read and apply.

It works very well except a bug that's very easy to replicate:

Click to add any conditions that has a value, such a Frightened. The circle with the condition value will not appear. You can click multiple times to add the conditions with a value above one, the circle will not appear.

If you close and open the condition HUD, the circle with the condition value will appear and will properly change its value as the condition is left or right-clicked. 

If possible, it is best that the condition circle appears on the icon's upper right corner rather than the text fields' upper right corner. 

![image](https://user-images.githubusercontent.com/4083812/109928320-01c92a00-7cce-11eb-9a0a-51fb1e2cc3ab.png)

**Comment by ironmonk88** [comment]
Position of the circle has been moved.
But I can't replicate the issue of the circle not showing.  Is it still a problem with the latest version?

**Comment by apoapostolov** [comment]
No it is no longer an issue in the latest version. All works perfectly now.

**Comment by ironmonk88** [comment]
Closing this as I think it's all working as expected now.  :-)
