### ISSUE TITLE
[BUG] Module Management Changes

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#241]
I'm not sure this feature is working properly? Everything looks exactly the same for me regardless of whether its enabled or not. 

![image](https://user-images.githubusercontent.com/99844555/213901612-3b85c937-eeaa-4e15-aa1b-db6a75ba752b.png)

![image](https://user-images.githubusercontent.com/99844555/213901622-4244330c-e6bd-4a1c-bca5-23ec68d8d5c2.png)

Foundry 10.291
Little Details 10.5
FTC
Tested in 5e and PF2.

**Comment by ironmonk88** [comment]
It's sort of working.  Found a couple of issues that should be fixed.
You need to expand the module list to see any of the information.
![image](https://user-images.githubusercontent.com/75920956/213933250-e85b63cd-e84c-4368-b5ee-5b1ce77768fd.png)

**Comment by ironmonk88** [comment]
Should be fixed in the most recent release.
