### ISSUE TITLE
[BUG] Setting Conflict with Sound Enhancements

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#242]
When ~DF Settings Clarity~ Monk's Sound Enhancements is enabled, the "Additional Features" header is missing.

# Disabled

![image](https://user-images.githubusercontent.com/99844555/214110846-b87a0014-270b-493f-9b73-c0b5e0ff6939.png)

# Enabled

![image](https://user-images.githubusercontent.com/99844555/214110986-50a2bce3-92f3-4859-8294-cced43d6d0a6.png)

Foundry 10.291
Little Details 10.5
Sound Enhancements 10.1

**Comment by ironmonk88** [comment]
Should be fixed in the most recent release.
