### ISSUE TITLE
[BUG] Cant change the size of the token highlight on player token

### ISSUE THREAD

**Issue by andrinhoo** [ironmonk88/monks-little-details#243]
Not sure if this is indended, but when i change the size of the combat token highlight, it just changes for the hostile tokens
![bug2](https://user-images.githubusercontent.com/123441168/214223474-d3b9eca7-00b9-435f-b730-00d61393e172.png)
![byg1](https://user-images.githubusercontent.com/123441168/214223478-7096aaa0-46f4-4965-9759-373e445a9f9a.png)

At the screenshots, the size was set to 2.0, but the player token (the one with blue borders) looked like the 1.5 size, and it looks like this on all sizes

**Comment by ironmonk88** [comment]
Are you sure those tokens don't have a custom highlight size set?

**Comment by andrinhoo** [comment]
ooooh i just found the option to chose the size at the token config menu

thx alot and sorry for the mistake

**Comment by ironmonk88** [comment]
No worries.
Closing the ticket.
