### ISSUE TITLE
[BUG] Error using combat marker when loading a scene where battle already started

### ISSUE THREAD

**Issue by Dialectikal** [ironmonk88/monks-little-details#244]
When I load my game in browser (or refresh) and a battle has already started on that scene, I see the following error in the console:
![image](https://user-images.githubusercontent.com/31572084/214745081-b87be5d9-d1e5-4ad3-ab5f-cb3c8fb26a6e.png)

1. Make sure Show Token Highlight is checked in Monk's Little Details settings
2. Create a scene with a few actors
3. Add actors to combat tracker
4. Begin combat
5. Refresh Foundry

 - Browser: Chrome
 - Foundry Version: 10.291
 - System: DnD5e 2.1.4
 - Module version: 10.5

I have tried Find the Culprit! It does not seem to be an interaction with other modules.
I have also tried with multiple different scenes and actors.

**Comment by ironmonk88** [comment]
Should be fixed in the most recent release.
