### ISSUE TITLE
Opacity Slider for Combat Bars

### ISSUE THREAD

**Issue by ShadeTheDM** [ironmonk88/monks-little-details#245]
Hey! The combat bar setting is a very nice qol change, however I find them really hard to see, especially for my players which can be quite tedious and slows things down.

I would like to suggest an opacity slider or a toggle feature for these combat bars so that they can be more visible for people that wish to see them more clearly in combat. I think it would be a nice touch to an already great feature for those who appreciate visual clarity.

Once again, thanks for the module! It's been amazing so far.

- Shade

**Comment by ironmonk88** [comment]
Should be added to the most recent release.
