### ISSUE TITLE
[BUG] Bloodspat not working on PF2e creature with 0 HP

### ISSUE THREAD

**Issue by yjeroen** [ironmonk88/monks-little-details#249]
**Describe the bug**
Bloodspat not working on PF2e creature with 0 HP.

**To Reproduce**
1. Do damage to a PF2e creature (e.g. a goblin) until its HP is 0

**Expected behavior**
Bloodspat

**Screenshots**
![image](https://user-images.githubusercontent.com/1303988/220442770-f4c5e1cd-89fb-4870-a38c-32f2752a7e42.png)

**Please complete as much of the following information as possible:**
 - Browser [e.g. chrome, safari] Chrome
![image](https://user-images.githubusercontent.com/1303988/220442837-f2dca64b-5179-41a7-be17-8829c5398515.png)

**Comment by ironmonk88** [comment]
Bloodsplats only works on something that has the dead or defeated status.
Little Details doesn't automatically set it to dead or defeated outside of combat.

**Comment by yjeroen** [comment]
Nevermind, didn't start combat
