### ISSUE TITLE
PF2, Condition Names - why do some conditions appear bold?

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#25]
Here's a screenshot, and this is probably not an issue but just a question - what is the logic behind some conditions appearing in a bold text?

![image](https://user-images.githubusercontent.com/4083812/109927735-50c28f80-7ccd-11eb-9d48-b5dd882fa5e0.png)

**Comment by rmasoni** [comment]
That isn't bold, it's either color or opacity that is different. Do they all behave the same when clicked?

**Comment by apoapostolov** [comment]
Yes, no difference in behavior between "bold" and normal entries.

**Comment by apoapostolov** [comment]
Btw if what you say is true (some icons are intentionally lightened to be better seen due to too dark) then the labels need to have strict color and opacity to avoid looking different.

**Comment by ironmonk88** [comment]
Those look like all the stackable statuses.  I'll need to check the styling but chance are I just missed something in the code.  They should all look the same.

**Comment by ironmonk88** [comment]
Styles should be fixed now.
