### ISSUE TITLE
[BUG] Incompatible with SWADE Immersion Module

### ISSUE THREAD

**Issue by dpotter895** [ironmonk88/monks-little-details#250]
I am unable to create SWADE "chase" scenes when I use Monks Little Details. When I try to generate the scene, all I get is a black view with a small white box in the center. I am expecting a dialog box to display where I can set settings for the chase view.

Console log does not show anything other than "Foundry VTT | Rendering ImagePopout".

To generate the scene, select a layout in the Chase compendium that SWADE Immersion Module (swim) creates.

**Comment by ironmonk88** [comment]
Monks Little Details adds the option to preview the scene image before you import.
Click the title to preview, click anywhere that's not the title to get the dialog.

**Comment by ironmonk88** [comment]
Or turn off the view compendium artwork.
![image](https://user-images.githubusercontent.com/75920956/229313235-cba89892-b494-4159-969a-4fc34f804359.png)
But this will turn off the artwork preview for every Scene Compendium.
