### ISSUE TITLE
Hide Death Saves on Actor Sheet

### ISSUE THREAD

**Issue by jinkergm** [ironmonk88/monks-little-details#254]
Going to start asking for Blind DM Rolls for death saves in 5e, but it still shows on the sheet. 

Would love an option to hide it in the actor sheet (if possible)

**Comment by ironmonk88** [comment]
I think this might be better covered by the Custom CSS module.  It's pretty easy to do in that module, and a little too edge case for Little Details.
```
/* Global Settings */
.actor.sheet .counter.death-saves { display: none !important; }
.tidy5e.sheet.actor .profile.dead .death-saves { display: none !important; }
```

```
/* User Settings */
.actor.sheet .counter.death-saves { display: flex !important; }
.tidy5e.sheet.actor .profile.dead .death-saves { display: flex !important; }
```
