### ISSUE TITLE
[BUG] Transform into Actor

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#256]
The right-click option `Transform into this Actor` results in this error when used by the GM. Also, this option isn't visible to a player even when they own the actor being right-clicked, not sure if that's intended.

![image](https://user-images.githubusercontent.com/99844555/229411240-74c39133-70db-4fbf-87ca-8f4393f16290.png)

Foundry 10.291
Little Details 10.8
D&D 5e 2.1.5

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
