### ISSUE TITLE
New Feature Request - It's Your Turn fade-out message to player when turn starts

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#26]
To accompany the sound effects, an optional "It's Your Turn" in bold blocky font that appears in the center of the screen and fades out in ~1 second. To make it more dynamic it could change size squeezing center-wards from 100% to 80% as it fades out. 

![image](https://user-images.githubusercontent.com/4083812/109932353-bebd8580-7cd2-11eb-97fe-12913a9ed64c.png)

**Comment by apoapostolov** [comment]
I know there is a Yellow Notification at the moment, but a ~1sec fade out big message on the screen catches the attention of players who watch the screen in peripheral vision (i.e. on the phone, standing from PC, etc.)

**Comment by ironmonk88** [comment]
Closing as this has been added.
