### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by Orionox** [ironmonk88/monks-little-details#260]
**Describe the bug**
Hides the price denomination. so when this is active, the denomination of the price of an item can no longer be seen. So instead of "1 CP," it shows "1." 

**Expected behavior**
The denomination of the price should still be visible 

**Screenshots**
![Normal](https://github.com/ironmonk88/monks-little-details/assets/20059838/f606b1d9-333b-48a5-bd54-c69317800508)
![Bugged](https://github.com/ironmonk88/monks-little-details/assets/20059838/258dfafc-b419-4a63-a82f-23d42b5a6dbc)

**Please complete as much of the following information as possible:**
 - Foundry Version: 10.291
 - System: 5e
 - Module version
 - Are there any errors in the console: Not that I see

**Comment by ironmonk88** [comment]
Should have been fixed in a previous version.
