### ISSUE TITLE
[BUG] Clear Folder button does not clear any folder data

### ISSUE THREAD

**Issue by yeeshue99** [ironmonk88/monks-little-details#261]
**Describe the bug**
When opening context menu for a folder, and selecting the option to "Clear Folder", nothing happens.

**To Reproduce**
1. Right click on any folder
2. Click on "Clear Folder"
3. Click "Yes" on dialog option
4. Notice items have not been deleted

**Expected behavior**
The expected functionality is for the folder to become empty after removing all folder contents.

**Screenshots**
![image](https://github.com/ironmonk88/monks-little-details/assets/35947745/d8f8874d-4d09-49d4-b8ce-eae06d913f37)
![image](https://github.com/ironmonk88/monks-little-details/assets/35947745/87db3559-ca97-415d-9ed5-a44b37f88459)

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry v10
 - D&D5e
 - Module version 10.4
 - No errors in console

**Additional context**
Proposed fix on line 807 of monks-little-details.js

Personal workaround is to change d.folder -> d.folder?.id

This recreated the desired results in my personal world.

**Comment by msprijatelj** [comment]
I know this is fixed and waiting for a release, but I wanted to chime in that this also occurs in my following world, in case it matters at all for the fix:
- Firefox
- Foundry v10.303
- Lancer v1.6.1
- Module Version 10.09
- No errors in console

**Comment by ironmonk88** [comment]
Fixed in the latest release.
