### ISSUE TITLE
Incompatibility issue with the 3.5e Game System.

### ISSUE THREAD

**Issue by Oryan77** [ironmonk88/monks-little-details#266]
Activating the "Change Core CSS" option from settings removes the "size" text on character sheets.

For example, a medium sized PC/NPC will have the correct token size set, but the text for "medium" is missing in the character sheet's 'Attributes' tab for both the "Size" dropdown menu, and the "Actual Size:" dropdown menu. 

The dropdown choice still works; this module just removes the text once chosen from the dropdown.

**Comment by ironmonk88** [comment]
Fixed in latest release.
