### ISSUE TITLE
Reorganize "Alter The Token HUD Status Effects" Section

### ISSUE THREAD

**Issue by kajishun** [ironmonk88/monks-little-details#267]
**Is your feature request related to a problem? Please describe.**
The problem is that I need to be able to activate some but not all of the Alter The Token HUD Status Effects options. As written, I can only activate these if I also show detailed status effects. I need to be able to suppress that and enable Allow to Clear All Effects and enable Sort Statuses. I also noticed that enabling the main item and sorting in columns automatically alphabetizes the markers. I do not see this in any descriptions; assumption to sort this way ought not be assumed.

**Describe the solution you'd like**
Please reorganize, add a section selection to turn on/off Alter the Token HUD Status Effects. Under that new subsection, separate out detailed status effects and clear all effects. Then add all applicable Token HUD Status Effects down to Add Extra Statuses. Please add another option to sort alphabetically or leave as-is.

**Additional context**
This is currently an all-or-nothing proposition. Ought to be able to select only the options one really needs without the extra verbiage from the details.

**Comment by ironmonk88** [comment]
Added the Clear all Effects to it's own setting.
