### ISSUE TITLE
[BUG] Compendiums disappears with the latest updated of Monk Little details

### ISSUE THREAD

**Issue by gris-x** [ironmonk88/monks-little-details#270]
The Compendium pack tabs comes up empty

**To Reproduce**
1. Go to 'Compendium Tab''
Nothing shows

**Expected behavior**
Compendium list to show (it does when Monk little details is disabled)

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version v11.301
 - System D&D5e
 - updated this morning
 - no errors showing

**Comment by miklam** [comment]
Getting the same error, uninstalled all modules and reinstalled only this one.

Foundry version 11.299, System D&D5e.

**Comment by Avitale34** [comment]
same

**Comment by ironmonk88** [comment]
I can't replicate.  But I'll try and track down what's happening.
In the mean time you can just turn the feature off and still use the module.
![image](https://github.com/ironmonk88/monks-little-details/assets/75920956/3f88ff64-b6f1-4045-aa1d-efd4532ff314)

**Comment by Deadlander** [comment]
I got the same error. Tracked it down in the Console:
![image](https://github.com/ironmonk88/monks-little-details/assets/13036735/baf732b2-0a1a-459c-a010-f448e2f842c3)

**Comment by lovethebomb** [comment]
In my case, after debugging and inspecting, it looked like some of the compendium packs had no `metadata` attributes.
Perhaps old compendiums that were migrated incorrectly? I do not remember errors while migrating from v10 to v11.

I had a few compendium packs throwing, like `ItemPiles`, if it helps.

**Comment by Rubengam3r** [comment]
I get the same console error when enabled. But monks suggestion is a great work around

**Comment by ironmonk88** [comment]
I think this should be fixed?

**Comment by lovethebomb** [comment]
I've re-enabled `Additional Sorting` and indeed, no errors. 
I think we can close this!

```
Foundry 11.306
Monk Little Details 11.04
```

**Comment by ironmonk88** [comment]
Closing this as it looks like it's working.
