### ISSUE TITLE
[BUG] Move with M not working

### ISSUE THREAD

**Issue by Avitale34** [ironmonk88/monks-little-details#271]
**Describe the bug**
Using the M move to move tokens is not working.

**Comment by ironmonk88** [comment]
Have you used FTC?
What system are you using?
What version of Foundry are you using?
Any errors in the console?
Are you using it as the GM (Players don't have access to this)?
Did you check that the key is set in the key configuration?
Are you holding down the M key and clicking for the token to move, or dragging and dropping while holding down the key?

**Comment by ironmonk88** [comment]
Closing this as there's no follow up and not enough information to track down the issue.
