### ISSUE TITLE
[BUG] new effect description text not showing in HUD

### ISSUE THREAD

**Issue by KJTailor** [ironmonk88/monks-little-details#273]
**Describe the bug**
after updating to Foundry V11, the text naming the different effects in the HUD does not appear anymore.

**To Reproduce**
no idea how you would replicate that, sorry

**Expected behavior**
Normally you would expect the text description of each effect to be visible, such as the module intends to do.

**Screenshots**
![image](https://github.com/ironmonk88/monks-little-details/assets/87787745/59d1fa42-f11b-4252-8f4f-71691a5a58a3)

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version: V11
 - System DnD5e 2.2.2.
 - Module version 11.04
 - Are there any errors in the console
![image](https://github.com/ironmonk88/monks-little-details/assets/87787745/df10bee4-18e1-402a-80a2-24ea4312ca43)
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.
yes. I have tried multiple full runs, but every time, the CulpritFinder would signal a modul as the cause, but if I'd deactivated that module, the issue would reoccur. Another run of the CulpritFinder would spit out the next module in the alphabet, after the previous one, with the same result. Interestingly, the modules both were 'drag' modules, namely 'drag ruler' and 'drag transfer', but maybe that is only because of their position in the list? I know, not very conclusive, sorry

**Comment by Fridan99** [comment]
Same issue (the name of the effects does't appear)

Dnd5e system 2.3.0

Foundry v11.307

Monk little details 11.04

**Comment by KJTailor** [comment]
interesting to know. I/we should ask CL&T's creator as well I guess?

**Comment by KJTailor** [comment]
That is good news in a way, at least now we know who to contact about the issue, to hopefully get CLnT's developer working on the issue in some way too.
Thanks for highlighting this

**Comment by JaydHawk** [comment]
I used condition lab once, but then uninstalled it a loooonnngggg time ago. However, I currently have this issue. Is there a way for me to reset somehow so I don't have this bug?

**Comment by MythicalRollers** [comment]
I was able to reproduce this issue and resolve it with one caveat that I have yet to see anyone else mention.  For me. Dfred Convenient Effects was also adding to the list.  I have this only because d&dbeyond importer wants it, I do not actively use it. I set it to None under status effects in the settings for it, and my list is visible again. So for me the issue was related to Monk's, Dfreds, and Condition Lab & Triggler.

**Comment by ironmonk88** [comment]
Looks like an issue with Condition Lab & Triggler.
The effects are being added with the `label` property and should be added with the `name` property.  Foundry doesn't add `title` to the status unless it has a name property, and MLD uses the `title` property of the element to add the text.
Not a lot that MLD can do at that point if it doesn't have the information it needs.

**Comment by MythicalRollers** [comment]
Just to clarify.  MLD and CLT work just fine for me once I told DFreds to NOT modify Status Effects.
Foundry: 11.308
D&D5e: 2.3.1
MLD: 11.04
CLT: 1.4.1
DFREDS: 5.1.0
<img width="667" alt="image" src="https://github.com/ironmonk88/monks-little-details/assets/106455111/9db7f750-a37f-46b8-8628-64991e403a78">

**Comment by ironmonk88** [comment]
Huh.  Yeah it might be a DFred's issue.  Or some combination between them.
Regardless... it's nothing that MLD can do.  MLD just uses the information it's given, and if the information given doesn't exist... there's not much it can do.

**Comment by KJTailor** [comment]
I wrote a collated bug report to DFred, hopefully they can do something about it?

**Comment by ironmonk88** [comment]
It's a bit weird.
Apparently the correct usage is `label` and not `name`.  Although I can add the `name` field to Condition Lab and it fixes things.
And MLD uses `label` and DFreds has no issues with that.

**Comment by JaydHawk** [comment]
I opened a brand new world in both Custom System Builder and Dnd5e. I ONLY activated monk's little details. I still have this issue. ![image](https://github.com/ironmonk88/monks-little-details/assets/121692476/22865d1d-4f35-4df1-b069-332ffa185c42)

**Comment by KJTailor** [comment]
Somehow the issue is resolved :)
