### ISSUE TITLE
[BUG] Popping out Actor tab does not work properly; renders last open Actor instead

### ISSUE THREAD

**Issue by TEUSnoopy** [ironmonk88/monks-little-details#274]
**Describe the bug**
Popping out the Actor tab via right-click does not work, opens last Actor sheet instead

**To Reproduce**

1. Right-click on Actor tab
2. Actor sheet opens instead of Actor tab

**Expected behavior**
Right-click on Actor tab expected to present popped-out Actor tab in a movable window within the UI

**Screenshots**
None required

**Please complete as much of the following information as possible:**
 - **Browser** [Chrome 115.0.5790.111]
 - **Foundry Version** [11.307]
 - **System**: D&D5e
 - **Module version**: 11.04
 - **Are there any errors in the console**: [No errors, but unexpected commands: 
 "_Foundry VTT | Rendering ActorSheet5eCharacter
foundry.js:7602 
Foundry VTT | Retrieved and compiled template systems/dnd5e/templates/actors/character-sheet.hbs_"]
- Testing with only MLD active.
Thank you for looking!

**Comment by ironmonk88** [comment]
That's literally a feature of Little Details.

Turn it off with this setting.
![image](https://github.com/ironmonk88/monks-little-details/assets/75920956/39ef827b-da57-4120-bb76-01110f66175f)

**Comment by TEUSnoopy** [comment]
Oof, so it is. My apologies. Would not expect this to be useful from my perspective. Thanks for the time.
