### ISSUE TITLE
[BUG] Show Scene Palette option does nothing

### ISSUE THREAD

**Issue by dineshm72** [ironmonk88/monks-little-details#276]
**Describe the bug**
The 5 dominant colors display doesn't show up anywhere.
This is a pretty minor thing, but I noticed it so thought I would report.

**To Reproduce**
1. Enable the Show Scene Palette option
2. Reload
3. Open config for scene
4. No 5 colors

**Expected behavior**
5 colors should be shown.

**Screenshots**
<img width="1103" alt="image" src="https://github.com/ironmonk88/monks-little-details/assets/2231877/81d909e7-e4f6-4940-8646-bdd0092e3c5c">
Not on grid or other config tabs either.

**Please complete as much of the following information as possible:**
 - chrome
 - 11.308
 - 5e 2.3.1
 - MLD 11.05
 - no console errors
 - only MLD (and forge) enabled

**Additional context**

**Comment by ironmonk88** [comment]
Did you press the button? 
![image](https://github.com/ironmonk88/monks-little-details/assets/75920956/db9a20b4-8c77-4626-abba-a63ccd8a37e5)

**Comment by ironmonk88** [comment]
Closing this as I can't replicate, and no response to the question.

**Comment by dineshm72** [comment]
Sorry, I forgot to update after testing.  The button wasn't doing anything when I made the issue, but it's working now.   Perhaps just some transient issue.  Thanks!
