### ISSUE TITLE
Feature Suggestion - quick way to set initial scene position

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#28]
Is it possible to add an option to the dropdown of a Scene that will change the Initial Scene Position to the current camera position and zoom?

![image](https://user-images.githubusercontent.com/4083812/110007705-a590f500-7d23-11eb-8f9c-6764a1804850.png)

**Comment by ironmonk88** [comment]
I can, but it's way easier to add that to Scene Navigation.
I notice that your scene buttons are not the standard, and I'd rather not override any styling that you'd rather have.  Which module is that from?  Or is it a system setting?

**Comment by apoapostolov** [comment]
The styling is from PF2. I am not using Scene Navigation, I will turn it on now and start using it to see how it would fit there.

**Comment by apoapostolov** [comment]
I moved the request to here: https://github.com/ironmonk88/monks-scene-navigation/issues/3

**Comment by ironmonk88** [comment]
Closing it here.  It's been added to scene navigation and should be available with it's next release.
I'll work on maintaining the styling of the system it's in.

**Comment by ironmonk88** [comment]
Is the styling from a PF2E module?  I can't seem to figure out where to change the style.
