### ISSUE TITLE
[BUG] Clear All Statuses, D&D 3.5

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#282]
Fails to remove and produces errors when using 3.5's new buffs item type.

https://github.com/ironmonk88/monks-little-details/assets/99844555/753a8f3e-98f1-44ef-a2e1-28899265ad3f

Foundry 11.315
LD 11.05
D&D 3.5 2.4.2

**Comment by ironmonk88** [comment]
Fixed in the latest release.
