### ISSUE TITLE
[BUG] Pause Border

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#283]
The color does not update live if the game is unpaused when the color is changed.

https://github.com/ironmonk88/monks-little-details/assets/99844555/68b126a4-cc21-4732-8115-cb391e019ea5

Foundry 11.315
Little Details 11.07

**Comment by MrZeyami** [comment]
I can confirm this happens sometimes on FF. Refreshing fixes the issue for me. Other times it updates normally.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
