### ISSUE TITLE
[BUG] In DnD5e 3.0.0 Inventory Item popup menus are unreadable when this module is enabled

### ISSUE THREAD

**Issue by flyingsquad** [ironmonk88/monks-little-details#287]
After converting to DnD5e 3.0.0, when you click the three dots menu on the right side of items in the Inventory, Features, etc., tab the popup menu is rendered dark blue with dark gray text, making it nearly impossible to read.

**To Reproduce**
Install DnD5e 3.0.0.
Open a character sheet
Go to the Inventory tab.
Click the three dots menu for an item in the inventory.
The menu is rendered with dark blue background and dark gray text, except for the highlighted item, which is visible.

This happens even if I turn off the replacement CSS feature.

**Expected behavior**
The menu should be rendered with contrasting colors.

**Screenshots**

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry Version v. 11.315
 - DnD5e 3.0.0
 - Module version 11.07
 - No errors in the log
 - This happens if this is the only module enabled.

![Screenshot 2024-01-31 233525](https://github.com/ironmonk88/monks-little-details/assets/135713857/31277ed7-bdf6-42c0-855e-be86f827290b)

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
