### ISSUE TITLE
[BUG] Incorrectly places exhaustion icon in token hud in dnd5e 3.0.x

### ISSUE THREAD

**Issue by strongpauly** [ironmonk88/monks-little-details#289]
**Describe the bug**
When altering the token huds status effects, applying levels of exhaustion moves the icon from the left to the middle of the effect text.

**To Reproduce**
1. Enable "Alter the token HUD status effects" in module settings.
2. Select a token
3. Open the token hud
4. Apply a level of exhaustion

**Expected behavior**
Exhaustion level 1 should be applied and icon should stay on the left 

**Screenshots**
<img width="819" alt="Screenshot 2024-02-17 at 17 42 37" src="https://github.com/ironmonk88/monks-little-details/assets/853954/c1fadeea-4903-402e-be24-a00d3ad286df">

**Please complete as much of the following information as possible:**
 - Browser: Electron
 - Foundry Version: v11 315
 - System: D&D5e 3.0.3
 - Module version: 11.08
 - Are there any errors in the console: no
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: no

**Comment by ironmonk88** [comment]
Should be added to the latest release.
