### ISSUE TITLE
Bloodsplat not working

### ISSUE THREAD

**Issue by Avitale34** [ironmonk88/monks-little-details#29]
I am having trouble getting the Bloodsplat to work. Is there some set up you have to do before hand?

**Comment by ironmonk88** [comment]
What's happening with the bloodsplat?  Also, what system are you using?  The bloodsplat shows up if the token has a defeated status applied to it.  Either the dead status, or defeated in the combat window.

**Comment by Nargath** [comment]
I had the same thing, although not sure its Little Details' fault.
When an attack kills an NPC, its reducing them to 0.
Which technically isn't Dead. So the defeated/dead status isn't auto applying, which means the bloodsplatter doesn't kick in

**Comment by Gossetjr** [comment]
Hey Monk, I think I know what's up here and I'd like to make a request based on the same "issue."
As it is right now bloodsplat works when the GM sets the token in combat to "defeated" in the combat tracker.
My request is if you'd be able to make it so when a npc creature hits 0 hp it will automatically mark the npc as "defeated" and apply the bloodsplat. I'd also like to request that if the hp increases above 0 at anytime the "defeated" mark is then turned off and in doing so turning off the bloodsplat.

**Comment by ironmonk88** [comment]
Should auto set to defeated now, if the token is in combat, and is of hostile disposition, and reaches 0 HP.
Will also remove the defeated status if it heals any.
Probably still needs testing to iron out all the issues though.  :-)

**Comment by Gossetjr** [comment]
Excited to try it out!

**Comment by Avitale34** [comment]
Works Great!!

**Comment by ironmonk88** [comment]
If it's working now, closing the ticket.  :-)
