### ISSUE TITLE
Missing conditions (e.g. Blessed)

### ISSUE THREAD

**Issue by PawLoh23** [ironmonk88/monks-little-details#292]
I am no longer able to see certain conditions from my conditions screen. Mainly blessed but some others as well.

![Screenshot 2024-03-12 at 10 29 19 PM](https://github.com/ironmonk88/monks-little-details/assets/76824112/c0cc3c23-315b-4bc2-84d3-ae3cd98d3f75)

**Comment by Darrkstarr** [comment]
> I am no longer able to see certain conditions from my conditions screen. Mainly blessed but some others as well.
> 
> ![Screenshot 2024-03-12 at 10 29 19 PM](https://private-user-images.githubusercontent.com/76824112/312289807-c0cc3c23-315b-4bc2-84d3-ae3cd98d3f75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5OTA1OTYsIm5iZiI6MTcyMDk5MDI5NiwicGF0aCI6Ii83NjgyNDExMi8zMTIyODk4MDctYzBjYzNjMjMtMzE1Yi00YmMyLTg0ZDMtYWUzY2Q5OGQzZjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDIwNTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZTQ3YTU5ZTk5ZTkzZjFmY2JmZjA0NWI3ZmQ2YmEzYTNiNmJlNGE4NGFmNjZlNDQ3NDlhZmMzNjYxNmM0MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s_DVT9_edfJrzdkQYVDFlEWHlNeARWtspYNavbawqpA)

I am having the exact same issue

**Comment by ironmonk88** [comment]
That has nothing to do with Little Details.
The D&D system is removing Bless, and a bunch of other statuses.
If you want them back you can add them as custom effects in the Little Details settings.

**Comment by maxgoldberg** [comment]
Is it possible to get some clarification on this? Bless appears in the DND 5e 2024 handbook, and doesn't appear to be removed. What do you mean by "The D&D system is removing Bless, and a bunch of other statuses."? Thanks!
