### ISSUE TITLE
[BUG] Pause Icon Off-center

### ISSUE THREAD

**Issue by InstantZzz** [ironmonk88/monks-little-details#293]
**Describe the bug**
In Cyberpunk Red my pause icon is moved off-center when I enable the "Move Pause-Icon Up" feature.
**To Reproduce**
1. Start a game of Cyberpunk Red
2. Enable "Move the Pause Icon Up" in "Monks Little Details"

**Expected behavior**
Both the "Game Paused" text and pause icon should simply be moved up the center.

**Screenshots**

**Please complete as much of the following information as possible:**
 - Browser [Brave (chromium)]
 - Foundry Version [v11.315]
 - System [Cyberpunk RED - Core vv0.88.2]
 - Module version [11.08]
 - Are there any errors in the console [e.g. press F12 and look for red text] (No red text)
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. (No I have not)
 - 
![icon](https://github.com/ironmonk88/monks-little-details/assets/103078788/f88e933a-72e4-4e8c-9b5d-63faad819275)

**Comment by ironmonk88** [comment]
Should be added to the latest release.
