### ISSUE TITLE
[BUG] [v12] Status text is hidden and error is thrown on load

### ISSUE THREAD

**Issue by strongpauly** [ironmonk88/monks-little-details#295]
**Describe the bug**
Text on the status icons in token hud is missing and error is shown in console.

**To Reproduce**
1. Enable module and have "Alter the HUD status effects" setting enabled.

Error is shown in console:
```
LibWrapperPackageError: Error thrown in hooked function 'init' for hook 'init'. Error detected in module Monk's Little Details. It is likely this module has not been updated for FVTT Version 12 Testing 3.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/ironmonk88/monks-little-details
Report this issue here: https://github.com/ironmonk88/monks-little-details/issues

== Technical Details:
Detected by libWrapper.
Package ID= monks-little-details
Error= Can't wrap 'TokenHUD.prototype.refreshStatusIcons', target does not exist or could not be found.

    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at de (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at HUDChanges.init (hud-changes.js:74:28)
    at Object.init [as fn] (monks-little-details.js:159:24)
    at #call (foundry.js:608:20)
    at Hooks.callAll (foundry.js:565:17)
    at Game.initialize (foundry.js:8873:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)
```

**Expected behavior**
No error and status effects text is shown

**Please complete as much of the following information as possible:**
 - Browser - electrion app
 - Foundry Version - v12,322
 - System - D&D5e 3.1.2
 - Module version
 - Are there any errors in the console - see above
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction -  No.

**Additional context**

**Comment by CerberusWolfie** [comment]
This may be due to the changes in V12 that took place in removing the effects on tokens in favor of linking them to actors. https://github.com/foundryvtt/foundryvtt/issues/10396

I believe the issue is in the js/hud-changes.js since it is referencing the token directly instead of an actor sheet?

_I am unsure if this is the correct suggestion to make in a comment section. I haven't used GitHub for anything other than personal repositories._

**Comment by ironmonk88** [comment]
Should be added to the latest release.
