### ISSUE TITLE
Stretched screen QOL

### ISSUE THREAD

**Issue by Gossetjr** [ironmonk88/monks-little-details#301]
**The problem is one you know well. Center is split between both monitors.**
Every thing that opens, opens center "screen."

**Reposition Center OR Memorize Window Location**
Convincing foundry to align more to the left or the right if the resolution exceeds x value, would be neat. Of if you could assign an area The system will remember and any new popup/window will popup in that space.

**Comment by ironmonk88** [comment]
Should be added to the latest release.
