### ISSUE TITLE
[BUG] Altered Status Effects breaks status affect assignment via token in Starfinder 1e

### ISSUE THREAD

**Issue by GravityBlade** [ironmonk88/monks-little-details#303]
**Describe the bug**
When the module is active you are not able to assign a condition to a PC/NPC character sheet from the token.

**To Reproduce**
1. activate module in Sf1e game
2. bring PC/NPC icon on to a map
3. double click on icon to open character sheet
4. switch to Conditions tab in character sheet
5. right click on icon and click on Assign Status Effects to the right of icon
6. click on any condition listed there
7. observe that the condition on the character sheet is not updated

**Expected behavior**
Clicking on a condition in the Assign Status Effect should update the token's character sheet. 

**Please complete as much of the following information as possible:**
 - Foundry Version: 12.331
 - System: Starfinder 1e
 - Module version: 12.03
 - Are there any errors in the console: no.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: only occurs when that module is active, even if it is the ONLY module active.

**Additional context**
None.

**Comment by ironmonk88** [comment]
Fixed in the latest release
