### ISSUE TITLE
Request: Chat Message Time Stamps

### ISSUE THREAD

**Issue by cpcodes** [ironmonk88/monks-little-details#305]
The chat messages display message times using a "X units ago" format that is not always useful. A simple date/time format is much preferred. There is a module, [Chat Message Timestamp](https://foundryvtt.com/packages/chat-timestamp/) that does this, but it does not appear to be maintained, and is such a small feature that it would be nice to reduce the number of modules installed by integrating it into another module. This seemed like the best one to me, though I can see an argument for the Chat Timer mod as well. The CMT module works well enough, but the module.json hasn't been updated since V10 and so it no longer appears in the module list for V12.

Please add Chat Message Timestamp (abandoned module) functionality to Monk's Little Details (or Monk's Chat Timer), or if there is another currently maintained module from another developer that you think would be a better fit for this functionality, please let me know and I can open a request there.

**Comment by ironmonk88** [comment]
Added as a tooltip in the latest release
