### ISSUE TITLE
[BUG] HUD-CHANGE.JS pb ligne 51 for translation other language

### ISSUE THREAD

**Issue by Jemipet** [ironmonk88/monks-little-details#306]
**Describe the bug**
HUD-CHANGE.JS pb ligne 51 for translation other language.

**To Reproduce**
Example in French:
The conditions are in English.

A wise coder advises to replace line 51 in "modules/monks-little-details/js/hud-change.js":
let title = $(img).attr('data-tooltip') || $(img).attr('data-status-id') || $(img).attr('title') || $(img).attr('data-condition');
by: 
let title = $(img).attr('data-tooltip') || $(img).attr('title') || $(img).attr('data-status-id') || $(img).attr('data-condition');

**Expected behavior**
Non-English speakers would appreciate this change so that they can post the terms in their language.

**Screenshots**
![image](https://github.com/user-attachments/assets/392f65e3-723c-451e-9d53-0f7899ae27c3)

Merci

**Comment by davidR1974** [comment]
additional information : that happens for pf2e system.. other systems tested (like dnd5e) works fine with translated strings for effects.

**Comment by Jemipet** [comment]
OK merci, donc incompatible PF2.
C'est noté.

**Comment by ironmonk88** [comment]
Fixed in the latest release
