### ISSUE TITLE
[BUG] Clear all button doesn't clear statuses added by Condition Lab & Triggler

### ISSUE THREAD

**Issue by strongpauly** [ironmonk88/monks-little-details#307]
**Describe the bug**
Any custom conditions added by Condition Lab & Triggler are not cleared when the clear all button is clicked

**To Reproduce**
1. Enable Monks Little Details and Condition Lab & Triggler modules.
2. Configure Condition Lab & Triggler with a custom condition.
3. Apply custom condition on a token.
4. Click Clear all button

**Expected behavior**
Custom condition should be cleared.  

**Actual behavior**
Custom condition is still applied.

**Please complete as much of the following information as possible:**
 - Browser: Electron
 - Foundry Version: v12.331
 - System: D&D5e v4.0.4
 - Module version: 12.0.3
 - Are there any errors in the console: No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: No.

**Additional context**
This is probably down to the appending of `dnd5e` to the effect id and looking that up, which doesn't work for the custom effects.

**Comment by ironmonk88** [comment]
Fixed in the latest release
