### ISSUE TITLE
[BUG] Condition names use unfriendly string in PF2E

### ISSUE THREAD

**Issue by itsthekeming** [ironmonk88/monks-little-details#308]
**Describe the bug**
When using the expanded condition names with the PF2E system, I'm seeing the names rendered as unfriendly strings that are lowercased and lack correct spacing. I believe this is caused by line 50 of `js/hud-changes.js`:

```js
let title = $(img).attr('data-tooltip') || $(img).attr('data-status-id') || $(img).attr('title') || $(img).attr('data-condition');
```

While debugging, I can tell that the value of `data-status-id` is what is being set as the text. This results in, for example, `persistent-damage` being set as the text instead of `Persistent Damage`.

**To Reproduce**
1. Enable the expanded condition menu
2. Go to an token's condition menu

**Expected behavior**
The condition text should be in the friendly format, in this case I believe the value of `data-title`.

**Screenshots**
![CleanShot 2024-10-24 at 16 41 15](https://github.com/user-attachments/assets/dbf74a93-499a-4b05-b80d-804270127e40)

**Please complete as much of the following information as possible:**
 - Browser: Chrome 130.0.6723.59
 - Foundry Version: 12 Stable, Build 331
 - System: PF2E v6.4.1
 - Module version: 12.03
 - Are there any errors in the console: no
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: yes

**Additional context**
I think swapping the second and third items in the `||` chain would resolve this issue. I verified it by patching my module locally. I'm only using PF2E though, I'm unsure what the impact on other systems might be.

**Comment by ironmonk88** [comment]
Fixed in the latest release
