### ISSUE TITLE
[BUG] Quick Transform, PF2

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#309]
For some reason this is an option on PF2 actors located inside a compendium; does nothing and nothing in the console when actually used however. Does not show up on actor tab actors, as expected.

https://github.com/user-attachments/assets/a2bd4f67-0492-4526-9d04-1796017c7273

Foundry 12.331
PF2 6.5.0
LD 12.03

**Comment by ironmonk88** [comment]
Fixed in the latest release
