### ISSUE TITLE
Little Detail Proposal: Unhide in Combat Tracker if Token switched to Visible (and vice versa)

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#31]
Reason for this request - I tend to add a lot of invisible creatures that haven't joined combat yet to the tracker, then I reveal them and players complain they still don't see them in the combat tracker because the creature doesn't automatically become visible in tracker. 

The feature, when turned on: When a Token is added to the combat tracker when its token switches from visible to an invisible state and vice versa, the combat tracker hides or reveals the creature in the tracker. 

![image](https://user-images.githubusercontent.com/4083812/111070690-79236880-84db-11eb-85e3-49accc4c1ac9.png)

**Comment by ironmonk88** [comment]
I've updated the code to reveal, when a token is no longer invisible, but havn't changed it if the token is made invisible.
There's a lot of times where the token is made invisible mid-combat, but the turn order still stands.
I can see the automation for when it's revealed, but I think hiding would prove a little too invasive.

**Comment by apoapostolov** [comment]
Thank you. This implementation covers all the major issues I have with uncovering tokens in the combat tracker.
