### ISSUE TITLE
[Request] Add Control Keybindings for Region Layer

### ISSUE THREAD

**Issue by DanielTheBard** [ironmonk88/monks-little-details#310]
**Is your feature request related to a problem? Please describe.**
There are keybindings for all of the old layers, but there isn't one for v12's Region Controls layer.

**Describe the solution you'd like**
'Change to Region Layer' + 'Quick show Region Layer' added to Configure Controls, so as to apply keybindings to them.

**Additional context**
![monksLittleDetails_controls-example](https://github.com/user-attachments/assets/0e09f779-b28f-4658-8cb4-55bad7d32643)
Theoretically, if it's simple, I would also love integrated support for a few other modules (like the module does for Enhanced Terrain Layer [despite that module being heavily outdated]). Namely the 'Safety Tools layer' from [Safety Tools](https://foundryvtt.com/packages/safety-tools), the 'Effect Controls tools' from [Token Magic FX](https://foundryvtt.com/packages/tokenmagic/), the 'Sequencer layer' from [Sequencer](https://foundryvtt.com/packages/sequencer), and the 'Levels layer' from [Levels](https://foundryvtt.com/packages/levels).

**Comment by ironmonk88** [comment]
Added to the latest release
