### ISSUE TITLE
[BUG] M to Teleport, Various Token Size

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-little-details#311]
It seems that having multiple token sizes when using this, the odd token out gets out of position, If all of them are different, then they all go crazy (not shown).

https://github.com/user-attachments/assets/d7daa883-9bab-46c9-951b-9f7e10da7140

https://github.com/user-attachments/assets/3d7f101c-da1f-4590-b237-4a56891e784a

Foundry 12.331
MLD 12.03

**Comment by ironmonk88** [comment]
Fixed in the latest release
