### ISSUE TITLE
[BUG] When I add a new effect in monk's little details settings, it doesn't appear in the token effects list.

### ISSUE THREAD

**Issue by DarthBalrog** [ironmonk88/monks-little-details#312]
Hi,

When I add a new effect in **monk's little details** settings, it doesn't appear in the token effects list.
What can I do?

Module version: 11.09
Foundry Version: 11 Build 315.
D&D5e Version: 3.3.1
Browser: Chrome

Thank you.

**Comment by DarthBalrog** [comment]
> Hi,
> 
> When I add a new effect in **monk's little details** settings, it doesn't appear in the token effects list. What can I do?
> 
> Module version: 11.09 Foundry Version: 11 Build 315. D&D5e Version: 3.3.1 Browser: Chrome
> 
> Thank you.

I found the problem: "DFred Convenient Effects"  conflict.

**Comment by ironmonk88** [comment]
Closing this as it's not really an MLD issue per say.  It's another module making changes.
