### ISSUE TITLE
[BUG] Too much Status effects, but I don't know how to remove 36 of them.

### ISSUE THREAD

**Issue by DarthBalrog** [ironmonk88/monks-little-details#313]
Hi,

**Describe the bug**
In the bar next to the token I see 48 status effects.
But in the configuration of Monk's Little Details I see 12 (in edit effects).
Where do the remaining 36 come from?
How do I delete the ones I don't want to have on hand?

**Expected behavior**
I'd like to see only the status effects in edit effects of Monk's Little Details.

**Screenshots**
![Monks01](https://github.com/user-attachments/assets/08247d1a-4d4d-420e-bd40-b761dca249b2)

**Please complete as much of the following information as possible:**
 - Browser [chrome]
 - Foundry Version [11]
 - System [D&D5e]
 - Module version [11.09]

Thank you!

**Comment by ironmonk88** [comment]
Little Details only adds its own effects.  Those other ones are most likely from the actual system D&D.
There are other modules that will edit all effects.  MLD only adds its own.
Run "Find the Culprit" to confirm if there's another module adding additional effects
