### ISSUE TITLE
Compatibility issue with Arbron's Compendium Tools

### ISSUE THREAD

**Issue by JJBocanegra** [ironmonk88/monks-little-details#32]
For a reason unknow to me, the context menu that Arbron's Compendium Tools give to a compendium entry is no where to be seen when Monk's Little Details is active. I used "Found the culprit" to track it down to this module.

This wasn't happening the other day, so I suspect that the version v1.0.16 is the one that introduces the problem.

Versions:
- Monk's Little Details v1.0.16
- Arbron's Compendium Tools v0.3.1

What I expect to see when I right click a compendium item:
![image](https://user-images.githubusercontent.com/5797636/111077547-98c58b80-84f1-11eb-8065-4e3dca6ca2e0.png)

What I see when I right click a compendium item with **Monk's Little Details** activated:
![image](https://user-images.githubusercontent.com/5797636/111077539-89464280-84f1-11eb-9567-8e696dbb4f53.png)

Checking the changelog I think the problem resides with this change:
```
Added context menu to view scene artwork in a compendium. Always found it difficult to select a map if I wasn't sure what I was looking at. This should allow you to see the whole map before importing it.
```

Maybe it removed every other context menu item from the compendium.

I hope this get fixed soon because Arbron's Compendium Tools is totally essential for me :(

**Comment by ironmonk88** [comment]
I'll look into a nicer way of handling this.
In the meantime... you can turn it off in the settings.  It should be the last one listed for Monks Little Details.
![Compendium](https://user-images.githubusercontent.com/75920956/111080245-d65af200-84ba-11eb-900b-e97c04317a82.PNG)

**Comment by arbron** [comment]
I've been working on a library to help any modules that want to add context menu options to Compendium entries. You can check out the [repository here](https://github.com/arbron/fvtt-context-menu-library). Feel free to contact me on Discord if you want to discuss it: arbron#6515

**Comment by ironmonk88** [comment]
That would be awesome.  I'll look into it. A lot of other Entities will expose _getEntryContextOptions which makes life so much easier.
But the compendium entries go straight to creating the context menu.

**Comment by ironmonk88** [comment]
Switched this to using the inner text as the link instead of using right click.
I'm still going to check out the library Arbron mentioned.
