### ISSUE TITLE
Players getting error message from new auto mark defeated feature

### ISSUE THREAD

**Issue by Avitale34** [ironmonk88/monks-little-details#33]
I love this new feature but noticed my players are getting this error whenever a creature dies or they load a game with defeated tokens.
Error: User AVIII lacks permission to update Tokens in parent RCJKTSPN7ndMjCUf
    at Function._onUpdate (opt/foundryvtt/dist/database/odm/embedded.js:1)
    at async Socket.handleEvent (opt/foundryvtt/dist/sockets.js:1)

**Comment by ironmonk88** [comment]
This should be fixed now.  Forgot to wrap some code in an isGM.
