### ISSUE TITLE
Combat Detail: remove target during combat when passing to next combatant

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#35]
This is supported by Midi QoL but it is very 5E focused mod and I need this for other systems (PF2). Also it is a feature that doesn't need a big heavy mod for it to be supported. Monk's perfect for it. 

What it does is: when during combat the current actor changes when going back and forth, remove any targets on the screen.

**Comment by ironmonk88** [comment]
Should be available in the latest release.  It will remove all the GM targets when changing combatants.
