### ISSUE TITLE
Alphabetize conditions in columns

### ISSUE THREAD

**Issue by M0nk3yy** [ironmonk88/monks-little-details#38]
Hey Monk, loving this mod. It adds a lot of stuff I didn't know how much I wanted.

My suggestion: The conditions on the Token HUD are set to be in alphabetical order, going across in rows. To me it would make more sense to have them in columns.

E.G. The first column shows A-D, the final column shows R-Z etc.

**Comment by M0nk3yy** [comment]
There's already an option for this, I'm dumb. Thanks.

**Comment by ironmonk88** [comment]
Not dumb... that was just added last night for you.  :-) I just hadn't gotten around to posting to the ticket.
Let me know if it's working, there were some issues setting it up.

**Comment by M0nk3yy** [comment]
Looking great to me Monk, thanks!
