### ISSUE TITLE
Make pause icon relocation a toggle

### ISSUE THREAD

**Issue by DariusWolfe** [ironmonk88/monks-little-details#39]
Hello,

Recent update caused me a minor issue. I've integrated the location of the pause icon into my 'lobby' scene, and the change to the location puts the icon directly in the middle of my 'previously on...' synopsis. I had to turn off the CSS changes to restore it, but I overall liked the enhancements those added.

I'd appreciate if the movement of the pause icon was a separate option so could retain the Core CSS changes without having to have that moved as well. I also understand if this isn't something you're willing to do.

**Comment by ironmonk88** [comment]
I moved it 'cause half the time I was trying to figure out why things weren't moving.
Now, I'm spending half my time muttering that it's in the way.  Lol.
I think that was one of those, you don't realize what you have until you change it.
Putting it behind a setting is probably a good plan.  Should be available in the next release.

**Comment by ironmonk88** [comment]
Latest release is out, should be a toggle now.
