### ISSUE TITLE
New Detail - Click Anvil to Hide all control UI

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#41]
This is a proposal extremely useful for streamers using an AssistentDM account to dream or for groups that use TV tables. 

Clicking the anvil in the upper corner of the screen does the following:
- The anvil itself becomes 70% transparent so that it is felt but not seen on the screen
- The Toolbar icons on the left edge of the screen is no longer shown
- The Macro bar at the bottom is no longer shown
- The Scene controls are no longer shown
- Optional - The whole field of the chatbox disappears so the dice and chat messages can extend to the bottom. Make sure that Dice Calculator (Dice Tray mod) and DF Chat Enhancements mod are also hidden as part of hiding the chat field and its options.

**Comment by ironmonk88** [comment]
Isn't there another module that does this?

**Comment by ironmonk88** [comment]
How about Monk's Common Display?
https://github.com/ironmonk88/monks-common-display/releases/latest/download/module.json

Has not been released yet.  So you'll have to install in manually, but I thought I'd give you first chance to make suggestions.

**Comment by ironmonk88** [comment]
Monk's Common Display has been released.
Closing this ticket.
