### ISSUE TITLE
Defeated status automation doesn't add skull overlay to token

### ISSUE THREAD

**Issue by Maghawk** [ironmonk88/monks-little-details#43]
Title says it all. 
If I click defeated myself, it works, but with the automation it only sets defeated in the initiative.

**Comment by ironmonk88** [comment]
This was kind of designed that way.
But I'm having second thoughts about it.
Assigning the defeated in combat status is easy, setting the dead status isn't as easy because each system handles it slightly differently.
I'll look into it though.

**Comment by ironmonk88** [comment]
Setting the defeated status should now also set the token status.

**Comment by Maghawk** [comment]
https://user-images.githubusercontent.com/81623344/119270573-42618100-bbf5-11eb-87ce-a9b2e4ec5cdd.mp4

No luck :( 
Video attached, all modules except this one deactivated just in case (but also happens with other modules on).
Maybe a system thing then? pf2e for me

**Comment by ironmonk88** [comment]
Can you check if this is still an issue with the latest version?

**Comment by Maghawk** [comment]
It’s working in 0.8.7, awesome! Only just updated to that, unsure how soon I’ll be going to 0.8.8 but I imagine they aren’t that different?

**Comment by ironmonk88** [comment]
Yayyy!!  Glad it's working.
I don't think there was much difference.  Just some some error fixing.

Closing the ticket.  :-)
