### ISSUE TITLE
DM doesn't see notifications not hear sounds

### ISSUE THREAD

**Issue by miguel-pinto-prodmad** [ironmonk88/monks-little-details#45]
As a DM, I don't see any notification when a monster turn is next not when the monster tur arrives.

On the same note, I also don't hear any sound when a new round starts, a turn is next nor when it starts.
If I open another browser and play with a player I can hear all sounds and see all notifications.

**Comment by ironmonk88** [comment]
As a GM you shouldn't see the monster turn notification.  
That would be a lot of sounds and notifications displaying every turn.
It gets really distracting.

The sounds are for the players that only have one token to control in a battle and sometimes get distracted when waiting for a whole bunch of other tokens to move before their turn comes up again.

**Comment by miguel-pinto-prodmad** [comment]
@ironmonk88 I agree with you on the monster side, but I think it would be still useful if the DM heard at least the New Round sound (or have an option to control if he wants to hear it or not).

It's a suggestion. Your choice to include it or not, of course.

thanks

**Comment by apoapostolov** [comment]
I agree with @miguel-pinto-prodmad that the New Round sound is very nice touch for the GM. I personally would like to hear the "next turn" sound also, since sometimes players pass the turn without me looking at the combat tracker, and would like to know they did that. Both should be options, and off by default of course.

**Comment by ironmonk88** [comment]
Settings have been changed and sounds should be customizable.
