### ISSUE TITLE
ever since the libwrapper update combat turn animations dont animate

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [ironmonk88/monks-little-details#46]
i think this maybe something to do with the libwrapper update that recently released but the token blue spinning animation on when someone is in combat doesnt trigger anymore. its really useful to me. so id appreciate a fix :)

**Comment by ironmonk88** [comment]
That was an optimization fail.
The filename for the image was changed in the settings to be a .svg instead of a .png.
I've corrected it.  Latest version is available.
