### ISSUE TITLE
Wildcard sound

### ISSUE THREAD

**Issue by Shepardkx** [ironmonk88/monks-little-details#47]
It would a nice thing to have the sound picker in the character sheet allow for wildcard sound so that everytime you click the button, a different sound plays.

**Comment by ironmonk88** [comment]
It's definitely been on my wishlist of things I wanted to add.
Can't tell you when it'll happen, but wanted to let you know that it's on the list.  :-)

**Comment by ironmonk88** [comment]
Happened sooner than I thought.  You should be able to use wildcard sound now.
