### ISSUE TITLE
BUG: All added condition icons do not show up correctly.

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-little-details#49]
All of the extra condition icons included with this module do not scale properly, and so you only see the top left corner of them.

**Comment by ironmonk88** [comment]
Which system are you using?  And is there another module that's affecting the icons, 'cause they look okay to me.

Can you send a picture of what you're seeing?

**Comment by ralph2190** [comment]
@ironmonk88 I disabled all modules and only enabled this one and still see the issue. Screenshot embedded below. I am using the D&D 5th edition system.
![image](https://user-images.githubusercontent.com/11889617/117530982-c684f900-afa5-11eb-9b76-4167ef6a7bb6.png)

**Comment by ralph2190** [comment]
Interesting data point @ironmonk88. When logging in as a player via Chrome, I can see the effects correctly sized. To clarify, the issue I screencapped above was taken from the Foundry Windows Client (which I primarily use for DMing).
![image](https://user-images.githubusercontent.com/11889617/117531515-6774b380-afa8-11eb-8ca3-eb69d3d31f9f.png)

**Comment by ironmonk88** [comment]
That was a weird one.  Thank you for catching that it was only using the Foundry Windows Client.
Turns out the images I was using didn't have the width and height set.
Updated that and it all looks good.
Changes will be in the next release.

**Comment by ironmonk88** [comment]
Should be fixed now.
Latest release is out.
