### ISSUE TITLE
PF2E conditions

### ISSUE THREAD

**Issue by fireman644** [ironmonk88/monks-little-details#5]
Your conditions idea is brilliant but it is not working with PF2E.  I've disabled all mods but yours and it still won't make a list.  Thank you.

**Comment by fireman644** [comment]
Also, the CR in the combat tracker is not showing.

**Comment by ironmonk88** [comment]
CR isn't available for PF2E.  Only have the tables/calculations for DnD5e at the moment... but I'm working on it.  :-)
The condition changes also aren't available for PF2E because it messed things up horribly.  I opted to restrict it to DnD5e while I worked on fixing it up.

**Comment by ironmonk88** [comment]
CR should be available in the combat tracker now, and the status conditions should now be available in Pathfinder with version 1.0.15.
