### ISSUE TITLE
Maintain Position Consistency of Status Effects Selector with Core

### ISSUE THREAD

**Issue by tjlanza** [ironmonk88/monks-little-details#51]
It would be preferable if the interface showed closer to where it does in core - starting aligned with the top of the button that activates it, then extending down and to the right.

![image](https://user-images.githubusercontent.com/21128724/116147775-1dd5c000-a6ae-11eb-9790-bce199faee9a.png)

As it is drawn now, starting above the button, it creates potential conflicts with systems and other modules that expect core behavior.

![image](https://user-images.githubusercontent.com/21128724/116147880-3fcf4280-a6ae-11eb-928d-6e3c1486ebfd.png)

**Comment by ironmonk88** [comment]
Should be fixed now.
Latest release is out.
