### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by JackrabbitSlim68** [ironmonk88/monks-little-details#53]
My players are seeing the following error whenever i mark an enemy dead in the combat tracker and remove that enemy.
![20210512_184412](https://user-images.githubusercontent.com/81382014/118160945-d5b7dc80-b3d3-11eb-99b8-f3bc16720454.jpg)

**Comment by ironmonk88** [comment]
Figured out that it was an issue setting the glyph for the bloodsplat.
Code has been fixed and will appear in the next patch.

**Comment by JackrabbitSlim68** [comment]
Thanks for the fast response!

**Comment by ironmonk88** [comment]
Should be fixed now.
Latest release is out.
