### ISSUE TITLE
In 0.8.x conditions lack names

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#56]
In 0.8.x conditions lack their names when using the broader format for condition lists that has names next to icons.

**Comment by drveoj** [comment]
> 
> 
> In 0.8.x conditions lack their names when using the broader format for condition lists that has names next to icons.

this... and the 'Clear All' tab/button never appears.

**Comment by ironmonk88** [comment]
Should be fixed now.  Current release supports 0.8.5
