### ISSUE TITLE
Mark Defeated Not Working...sorta (PF2E)

### ISSUE THREAD

**Issue by Cosmic-Lattee** [ironmonk88/monks-little-details#59]
So here is a interesting one. 

The mark defeated is working in one PF2e but not the other.

![image](https://user-images.githubusercontent.com/24766235/121196486-23d6c900-c836-11eb-9525-827df1863cd0.png)
This is a blank game with just Monk's installed.

![image](https://user-images.githubusercontent.com/24766235/121196830-6c8e8200-c836-11eb-8b94-d6e588ace4c2.png)
This is a old game from 7.9 that has been migrated to the newest version of Foundry/PF2E.

Regardless of settings I can't seem to get this one feature to work on new games I create. Very strange.

Foundry: 0.8.6
PF2E: 2.1.1.6052

**Comment by Cosmic-Lattee** [comment]
So it's strange my blank game didn't show this error while my current game that also doesn't have this addon working throws out this error when a NPC hits zero:

![image](https://user-images.githubusercontent.com/24766235/121369215-4550b700-c901-11eb-9032-07dc189e4236.png)

**Comment by ironmonk88** [comment]
Changes have been made, can you confirm if this is fixed?

**Comment by Cosmic-Lattee** [comment]
Yes looks like it is working now. Thank you for your hard work! 👍

**Comment by ironmonk88** [comment]
Yayyy!!!
