### ISSUE TITLE
Compatibility problem with Drag Ruler (Turn Sounds)

### ISSUE THREAD

**Issue by Sekierer** [ironmonk88/monks-little-details#61]
Ahoy,

If you are using Drag Ruler together with Monks-Little-Details and have the "next up" or "your turn" sounds active, it will play the sound EVERY time you move. It came up during our last session and afterwards I went to look for the culprit. I tested it on my module testing world, with only Monk's Little Details active and Drag Ruler. I don't get any error message in the console though.

I thought it's worth mentioning

**Comment by ironmonk88** [comment]
It looks like the update combatant function is being called and I wasn't limiting the type of call I was interested in.
Fixed and waiting for the next release.

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
