### ISSUE TITLE
Alter Token Hud Status Effects Not Showing Names

### ISSUE THREAD

**Issue by webmaster94** [ironmonk88/monks-little-details#62]
![image](https://user-images.githubusercontent.com/85364225/122120356-e8b53680-cdef-11eb-8024-6ed7961a18bc.png)

I checked in a test world with just this module enabled to ensure it wasn't a problem with another module. 

![image](https://user-images.githubusercontent.com/85364225/122120470-1601e480-cdf0-11eb-9b30-bc54cb9c2a15.png)
![image](https://user-images.githubusercontent.com/85364225/122120535-29ad4b00-cdf0-11eb-9d28-0ec71c02496b.png)

**Comment by ironmonk88** [comment]
Are there any errors in the log?
I've tried with a new 5e world and the names are showing for me.

**Comment by webmaster94** [comment]
No errors are being thrown to the console.

**Comment by ironmonk88** [comment]
It looks like the styles are being added properly, and the extra elements have been added, but that the title information hasn't been added.  Which is really weird.

Could you type `canvas.hud.token._getStatusEffectChoices()` into the console and let me know what it says?

**Comment by webmaster94** [comment]
This is the error I receive: 
![image](https://user-images.githubusercontent.com/85364225/122627443-0ba44c80-d075-11eb-9893-b2ea588679f1.png)
This occurs if a token is selected and if one is not. 

Interestingly enough, this error occurs whether or not the module is on or not. I will let you know since it is not clear in the image that I still get the tooltip stating the type of effect on hover whether the module is enabled or not.

**Comment by ironmonk88** [comment]
Has this been fixed?

**Comment by webmaster94** [comment]
After the latest update, this appears to have been fixed.

**Comment by ironmonk88** [comment]
Closing as this looks to be fixed.
