### ISSUE TITLE
Status not working properly with latest PF2e

### ISSUE THREAD

**Issue by erithtotl** [ironmonk88/monks-little-details#65]
They've altered the PF2e status tokens to use webp instead of PNG.  This is breaking your alter statuses function which is a shame, because I much prefer your layout.

**Comment by ironmonk88** [comment]
What seems to be happening?

**Comment by erithtotl** [comment]
Gah, sorry I can't believe put this in here and didn't give you any details.  See images below.  You have to refresh after enabling your status checkboxes to see the problem.

Oddly enough, the loading errors happen with your mod checkboxes enabled or disabled. 
![statuses wrong](https://user-images.githubusercontent.com/18316783/122650090-eeb45b80-d0fe-11eb-94b3-875cc2ed5393.png)
![loading errors](https://user-images.githubusercontent.com/18316783/122650091-f116b580-d0fe-11eb-90a6-589b97ac4496.png)

**Comment by ironmonk88** [comment]
Should be fixed now.
Things that worked correctly in one system... did not work correctly in others.

**Comment by ironmonk88** [comment]
This should be fixed int he latest version
