### ISSUE TITLE
No dice sounds with Monk's Little Details enabled

### ISSUE THREAD

**Issue by bugbeersandflagons** [ironmonk88/monks-little-details#66]
Hi,

Foundry 0.8.7, Monks Little Details v1.0.30.  While the module is running, I no longer get dice sound effects, and the following error is thrown to the console.  With the module disabled, the sounds work once more

> Uncaught (in promise) ReferenceError: message is not defined
>     chatLogNotify monks-little-details.js:417
>     call_wrapper libWrapper-wrapper.js:550
>     0 libWrapper-wrapper.js:162
>     postOne foundry.js:32290
>     _onCreate foundry.js:12973
>     callback foundry.js:8669
>     documents foundry.js:8620
>     _handleCreateDocuments foundry.js:8620
>     _createDocuments foundry.js:8516
>     create backend.mjs:96
>     createDocuments document.mjs:331
>     create document.mjs:430
>     processMessage foundry.js:32427
>     _onChatKeyDown foundry.js:32677
>     jQuery 2
> monks-little-details.js:417:21
>     postOne https://www.bugbeersandflagons.co.uk:30000/scripts/foundry.js:32294
>     InterpretGeneratorResume self-hosted:1485
>     AsyncFunctionNext self-hosted:695
>     (Async: async)
>     _onCreate https://www.bugbeersandflagons.co.uk:30000/scripts/foundry.js:12973
>     callback https://www.bugbeersandflagons.co.uk:30000/scripts/foundry.js:8669
>     callback self-hosted:1282
>     documents https://www.bugbeersandflagons.co.uk:30000/scripts/foundry.js:8620
>     map self-hosted:224
>     _handleCreateDocuments https://www.bugbeersandflagons.co.uk:30000/scripts/foundry.js:8620
>     _createDocuments https://www.bugbeersandflagons.co.uk:30000/scripts/foundry.js:8516
>     InterpretGeneratorResume self-hosted:1485
>     AsyncFunctionNext self-hosted:695
>     (Async: async)
>     create https://www.bugbeersandflagons.co.uk:30000/common/abstract/backend.mjs:96
>     InterpretGeneratorResume self-hosted:1485
>     AsyncFunctionNext self-hosted:695
>     (Async: async)
>     createDocuments https://www.bugbeersandflagons.co.uk:30000/common/abstract/document.mjs:331
>     create https://www.bugbeersandflagons.co.uk:30000/common/abstract/document.mjs:430
>     processMessage https://www.bugbeersandflagons.co.uk:30000/scripts/foundry.js:32427
>     InterpretGeneratorResume self-hosted:1485
>     AsyncFunctionNext self-hosted:695
>     (Async: async)
>     _onChatKeyDown https://www.bugbeersandflagons.co.uk:30000/scripts/foundry.js:32677
>     _onChatKeyDown self-hosted:1178
>     jQuery 2
>

**Comment by bugbeersandflagons** [comment]
I just updated to 1.0.31 and the issue persists

**Comment by ironmonk88** [comment]
1.0.32 should have fixed that.
Having issues with libWrapper integration.

**Comment by bugbeersandflagons** [comment]
Confirmed - updated to 1.0.32 and sound is now working again.  Thank you :)
