### ISSUE TITLE
"/timer" chat-command not working

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-little-details#68]
Versions:
![image](https://user-images.githubusercontent.com/44159008/122811913-53bfab00-d2d1-11eb-8e0d-554f6577626f.png)
![image](https://user-images.githubusercontent.com/44159008/122812189-a8fbbc80-d2d1-11eb-8f99-023db565cbba.png)

Command Used:
![image](https://user-images.githubusercontent.com/44159008/122812375-e52f1d00-d2d1-11eb-8806-94332641e545.png)

Error message:
![image](https://user-images.githubusercontent.com/44159008/122812047-7b167800-d2d1-11eb-96b0-f0b33c46ad8d.png)

Console message:
![image](https://user-images.githubusercontent.com/44159008/122812104-8e294800-d2d1-11eb-8fc9-0eb9117354c8.png)

I am probably doing it wrong...

**Comment by ironmonk88** [comment]
Omg.  No... I left out an important part.
You need to install the module "Library: Chat Commands".
My apologies, and I will leave this ticket open to remind myself to update the README and Foundry page.

**Comment by tagnullde** [comment]
No worries. It works that way.

Maybe some feature suggestions while I am here:

- Obey DM roll style (blind, self, etc)
- Add option for "/timer 5s, 5m, 5h"
- Add option for countdown instead of countup, maybe even alarmclock that generates a new card once it runs out
- Obey SimpleCalendar clock (like ingame vs. realtime time progression)
![image](https://user-images.githubusercontent.com/44159008/122815321-95525500-d2d5-11eb-9ce1-379cf9edbbdf.png)


Just some random thoughts...

**Comment by ironmonk88** [comment]
It should respect the DM roll.  I'll look into that
But I like the suggestions.
Honestly it was a spur of the moment, I need this for tonight, kind of programming.  But could definitely do with some polishing.

**Comment by ironmonk88** [comment]
Next version includes the option to count up or down.  The option to enter hours, minutes, or seconds, The option to add a message to the chat window.  And the option to add a second chat message when it completes.
Both the README and Foundry will be updates when the next version is released.

**Comment by ironmonk88** [comment]
Latest version has these updates.
Thank you again for the suggestions.
