### ISSUE TITLE
CR calculator does not appear to be working in 0.8.7

### ISSUE THREAD

**Issue by flamewave000** [ironmonk88/monks-little-details#69]
I really like having that CR calculator in the combat, but it seems to be broken in 0.8.7. This encounter is being shown as Epic, but should only be a Medium combat. The party is level 5 and there's just the 2 Yetis

![image](https://user-images.githubusercontent.com/3588046/122975346-405c2080-d361-11eb-8352-78e1dc86cefa.png)

**Comment by ironmonk88** [comment]
DnD5e?

**Comment by flamewave000** [comment]
Yeah, I'm using the D&D5e system

**Comment by ironmonk88** [comment]
Figuring out the levels of characters changed a bit from 0.7 and I had a bug in that code.  So players were always considered level 0.

**Comment by ironmonk88** [comment]
Latest version should have this fixed.
