### ISSUE TITLE
GM Move characters

### ISSUE THREAD

**Issue by HippyCraig** [ironmonk88/monks-little-details#7]
Hi,

I dont see a way to enable that feature and if I just try to use it, it doesn't seem to work with the M key.

**Comment by ironmonk88** [comment]
I tried to get it to work with the drag but it wasn't quite working.  I opted for just moving on a click.  So select the tokens you want to move.  Pan to the new location, and while holding down the m click, click on the canvas.  All the tokens should be teleported to that location.

At some point I'd like to get the drag and drop working, but for right now I wanted something that I could use.

Let me know if that's not the order of things you were trying, and I'll leave the ticket open to remind myself to re investigate the drag and drop issues.

**Comment by JJBocanegra** [comment]
I'm having the same issue, it doesn't seem to work with those instructions.

**Comment by ironmonk88** [comment]
I was wondering if it's another module running interference on the M key.
I'll add a setting to specify what key to use and see if that clears it up.

**Comment by JJBocanegra** [comment]
For some reason, it worked for me now... 🤔

**Comment by HippyCraig** [comment]
Nope still not working, I restarted foundry and still nothing

**Comment by JJBocanegra** [comment]
> Nope still not working, I restarted foundry and still nothing

Have you tried without having any other module active?

**Comment by JJBocanegra** [comment]
It's happening again, it doesn't work :(

**Comment by ironmonk88** [comment]
The option to change what key moves them has just been added.
Just to check and see that another module isn't using the m key.
Also updated the code so that it'll move the tokens as a batch instead of one by one.  It's a little faster and looks a little better.  Perhaps that small update will help.

**Comment by cs96and** [comment]
I'm having the same issue.  Pressing m and clicking somewhere on the map has no effect.  I have tried disabling all modules, changing the key, and also tried disabling Left Click to Release Objects in the core foundry settings, but to no avail.

**Comment by JJBocanegra** [comment]
@cs96and It works for me everytime now, did you tried to do it in an empty world with just this module installed? You have to press "M" while doing the click, some of my friend were confused and pressed and released "M" and then clicked.

**Comment by cs96and** [comment]
I did some playing around and it turns out that I can get it to work on the initial scene only.  As soon as I change scene then it no longer works.

**Comment by JJBocanegra** [comment]
You are right, I didn't saw it because I didn't change the scene.

**Comment by ironmonk88** [comment]
Well... that would do it.  I can't believe that in all my testing I didn't check what happens after I changed a scene.  Found the issue.  It's been patched and will go in the next release.
Thank you very much for finding that.

**Comment by ironmonk88** [comment]
Changes should be int he most recent patch.
