### ISSUE TITLE
Improve bloodsplat behavior after battle

### ISSUE THREAD

**Issue by rlach** [ironmonk88/monks-little-details#70]
When "show bloodsplat" option is turned on the monster properly turns into bloodsplat during battle, and relevant token becomes invisible.

Once battle ends hovering over the token will reset it to normal version, with no bloodsplat and the original image.
For comparison, if bloodsplat is turned off the skull icon will remain on all tokens even outside combat.

I don't know if it's possible to keep the splat effect outside of combat, but at the very least the tokens should revert to skull icon version. They are dead after all.

System info: foundry 8.7.0, pathfinder 2.4.0, monk's little details: 1.0.32

**Comment by ironmonk88** [comment]
This is a bug.
It's supposed to be setting the token status as well as the defeated status, but wasn't for some reason.
I tried to fix it in the latest version.

**Comment by rlach** [comment]
Still persists at 1.0.33.
This is how it works for me:
https://youtu.be/57B31dsrbW0

**Comment by ironmonk88** [comment]
That was a really interesting Pathfinder issue.  There's no status for dead, and I was expecting there to be one.
I think it's solved now.
Should be available with the next release.

**Comment by rlach** [comment]
I've tested it, and it works when I mark enemies as defeated or set their HP to 0.
