### ISSUE TITLE
Settings arent respected while module is active

### ISSUE THREAD

**Issue by roi007leaf** [ironmonk88/monks-little-details#72]
This is a weird one.
I turned on a few settings like the pause to the middle of the screen and turn to announce.
worked.
changed to those disabled, refreshed my game.
turn still announced and pause it stuck in the middle of the screen.
what info can I provide?

**Comment by ironmonk88** [comment]
DnD5e?  Can you check that this is still an issue with just Little Details active?
I tried to replicate it but the settings are saving correctly for me.

**Comment by roi007leaf** [comment]
Yes 5E.
Still happens with just  little details active

**Comment by ironmonk88** [comment]
Sorry... this is going to be a horrible question, but you did press the save button at the bottom?
I'm assuming yes, but it doesn't hurt to check sometimes.
Next suggestion would be to uninstall Little Details and install it again and see if that makes a difference.
This one is really weird.

**Comment by roi007leaf** [comment]
Lol yeah I pressed save.
Re installing didn't help I'm afraid

**Comment by ironmonk88** [comment]
It's really weird, there's nothing in Little Details that should be affecting that.  All the module does is get the setting.
Usually the process of saving settings is up to Foundry.

I'm assuming when you save the settings, the next time you load, the settings havn't been saved?  Like, this isn't a matter of the settings have been saved, but Little Details is ignoring the setting?

And Little Details is the only module this happens with?
And no errors in the console?

**Comment by roi007leaf** [comment]
All the check boxes ARE saved to the right values, but the functionality is not..

**Comment by tagnullde** [comment]
I don't think this is about MLD. I have this with Next-Up and I am investigating if there are other modules affected too.
Sometime when I save settings - they get saved. You can actually see a message in the console "Created Setting with id ..."

In like 80% of the time - this message doesn't show up.

**Comment by ironmonk88** [comment]
Closing this while cleaning up tickets.
I think this might not have been an issue with Little Details but might have been an issue with Foundry itself.
