### ISSUE TITLE
entire map displayed and visible to players when they press the w key

### ISSUE THREAD

**Issue by Asherlock** [ironmonk88/monks-little-details#73]
While running a game yesterday one of my players noticed this behavior. I can understand it being a feature for GMs but surely there's no good reason that those with the "player" role should have vision of every wall or even access to the walls tab. anyway, I went through my active modules and this seems to be the culprit. Genuinely great module though!
![image](https://user-images.githubusercontent.com/15909275/123832224-065cc280-d8fd-11eb-942d-8cd6b07d9dbc.png)

**Comment by ironmonk88** [comment]
Omg.  That's not cool!
I've changed the code so only GM's can activate it.
Will be available next update.

**Comment by ironmonk88** [comment]
Closing this as it's should have been fixed in a previous release.  :-)
