### ISSUE TITLE
Potential conflict with df-architect module

### ISSUE THREAD

**Issue by dirusulixes** [ironmonk88/monks-little-details#74]
fvtt 0.8.8
monks-little-details 1.0.33
df-architect 2.0.2

Lib-wrapper reports a potential conflict due to a detected non-libWrapper wrapping of 'Wall.prototype._onDragLeftDrop' by module 'monks-little-details'

**Comment by ironmonk88** [comment]
It shouldn't be an issue, but I've wrapped it with libWrapper just to be safe.

**Comment by ironmonk88** [comment]
Closing this as it's should have been fixed in a previous release.  :-)
And.. the functionality has moved to a different module.  Monk's Wall Enhancements should have this covered.
