### ISSUE TITLE
request:  display PF2e encounter threat

### ISSUE THREAD

**Issue by ditzer252** [ironmonk88/monks-little-details#75]
Hi!  I really love this module alongside tokenbar and I have a small request to make it even better for PF2e players...
Would you please consider updating the "Show Combat CR" so that it is compatible with the PF2e system? i.e., Encounter Threat:  Trivial, Low, Moderate, Severe, Extreme
The rules are here:  https://2e.aonprd.com/Rules.aspx?ID=498
Thanks for all you do.

**Comment by ironmonk88** [comment]
The new labels have been added.
It should technically be calculating properly, just wasn't using Pathfinder terminology.

**Comment by ditzer252** [comment]
Thank you!

**Comment by ironmonk88** [comment]
Should have been added awhile ago, just cleaning up tickets.
