### ISSUE TITLE
XP reward broken image link

### ISSUE THREAD

**Issue by Maghawk** [ironmonk88/monks-little-details#76]
XP rewards have some dead image links in, looks weird

<img width="300" alt="Screenshot 2021-07-04 at 13 27 54" src="https://user-images.githubusercontent.com/81623344/124390681-9d05f680-dce4-11eb-81c1-a7255ee10b0f.png">

FVTT 0.8.8
Pathfinder 2e 2.7.1.6493

**Comment by ironmonk88** [comment]
I'm thinking that's an incompatibility with another module.
There are images there that I don't add.
Is it doing that when Little Details is the only module?

**Comment by ironmonk88** [comment]
Closing this as it looks like a Chat Portraits issue and has been fixed.
