### ISSUE TITLE
Popout Combat Dialog should be locally scoped

### ISSUE THREAD

**Issue by DFreds** [ironmonk88/monks-little-details#8]
Personally, I don't think players should be forced to have their combat dialog popout just because me as the GM wants it to. I can change this by modifying your code easily enough, but I thought I'd bring it up as a possible feature request depending on your thoughts.

**Comment by DFreds** [comment]
Alternatively, have a setting that allows you to popout the dialog for GMs only.

**Comment by ironmonk88** [comment]
Makes sense.  I added both options.  GM can set how the popout happens (never, everyone, gm only, or players only) and individual players can set if they want to see it or not.
Will be available next patch.

**Comment by DFreds** [comment]
Awesome, thanks!
