### ISSUE TITLE
During combat, after deleting token from canvas cannot move that actor onto canvas from actors to create a new token

### ISSUE THREAD

**Issue by napolitanod** [ironmonk88/monks-little-details#84]
Issue:
This is during active combat. I have a token linked to an actor that is part of the combat and on the canvas. I delete that token. I then go to the actors area and find the actor for the token I delete. I drag that token onto the canvas. No new token is created. Console displays this error:

![image](https://user-images.githubusercontent.com/22696153/125714525-e4729a67-a6a5-453d-83cf-572321cd15c6.png)

Additional Steps to Recreate:
The way I can recreate this is by having one scene active where the players are (say, the landing page). As DM I go into another scene and start to prep the combat. I add the monsters and character tokens to the tracker and everybody rolls initiative. I start combat. I activate the scene I am on, bringing all the players to that scene. That seems to set up the issue I described.

Additional info:
Sometimes the players cannot select their tokens on the canvas when I activate the scene where the combat is started. This is why I delete the token and try to add a new one, because that clears the problem. But at this point I cannot readd the token until I refresh the browser, at which point I can add that (but if I delete another token I get the same issue until I refresh again). This may seem like a niche case but it has happened in each of my last 3 games enough where I could identify the steps to recreate and try it myself.

I use firefox. 
I am self hosted on AWS ec2 instance
I am on 8.8 and dnd5e 1.3.6
Monks little details 1.0.34 (currently compatible for 8.7 I know)

I do have other modules loaded, mostly common ones that are all at least 8.x compatible. 

I love your modules BTW and the effort you have put into them.

**Comment by ironmonk88** [comment]
That was an odd one.
So it looks like when Little Details checked on a combatant being deleted, it asked for the related token.  Since the related token was deleted, Foundry went ahead a created it again so that it could check on it.
And this token was there, but not there at the same time.  And caused the error because it didn't have everything set up properly.

I'm now checking on the raw related token, rather than using the handy function Foundry provides.

**Comment by napolitanod** [comment]
Sorry for the delay in response! Thank you for your time on this and all of your beautiful modules. I use so many of them that I had to become a Patreon!

**Comment by ironmonk88** [comment]
Closing as this was changed awhile ago.  :-)
Also thank you for becoming a Patreon!!
