### ISSUE TITLE
Bug : Token disappearing from the kanva

### ISSUE THREAD

**Issue by uniwars** [ironmonk88/monks-little-details#88]
Hello, GM and players regulary reports all or some of the tokens disappearing after changing tool (f5 solves the issue, but it comes back randomly after) the issue is only for the one switching tool

here an error I get in the console : 
https://cdn.discordapp.com/attachments/766088199264796692/867920864706953266/Error.png

I have an other very ennoying issue that may be related : some players or GM will not see some tokens on the kanva and will need to f5 to see all tokens, and each person could see a different set of tokens and even not see its own token as a player. The token are not and the kanva and not in monk's token bar either. I can't find a way to replicate but it happens pretty often.

**Comment by uniwars** [comment]
here the wrapper : 
![image](https://user-images.githubusercontent.com/65986545/126765598-004bf60a-18f3-4cf8-bc51-478545956c87.png)

**Comment by Xyxzor** [comment]
Getting this behavior as well. Very common.

**Comment by uniwars** [comment]
> Getting this behavior as well. Very common.

the error in the console or the disappearing tokens ?

**Comment by Xyxzor** [comment]
Disappearing tokens. I disabled the modules last session (this is increasingly becoming a major drag on our sessions), and the issue seemed to have clear up.

**Comment by uniwars** [comment]
> Disappearing tokens. I disabled the modules last session (this is increasingly becoming a major drag on our sessions), and the issue seemed to have clear up.

ironmon said on disocrd that it may come from bloodsplat or turn marker which touch to token
I'm trying to disable bloodsplat I'll see if the issue still happens

**Comment by ironmonk88** [comment]
So it looks like this is coming from the lichtgeschwindigkeit module and not Little Details.

**Comment by uniwars** [comment]
I don't have it installed

**Comment by Xyxzor** [comment]
Very well could be coming from either Little Details or TokenBar. Torch and Health Estimate, may be the culprits as well, but not sure if you have either of those installed @uniwars

**Comment by uniwars** [comment]
I have them except Torch, but the bug disappeared after disabling bloodsplat feature

**Comment by Xyxzor** [comment]
It didn't go away for me until I uninstalled both Monk modules, even had bloodspat disabled prior. Odd.

**Comment by ironmonk88** [comment]
Cleaning up tickets, but I believe this has resolved itself.  Either another module was causing interference, or Foundry itself had an unusual bug.  But I havn't heard of anyone encountering it in awhile.
