### ISSUE TITLE
Request: Per-user disable the round tracker from popping up.

### ISSUE THREAD

**Issue by hoshisabi** [ironmonk88/monks-little-details#9]
When I run, I often stream the game through Twitch. To do that, I log a user in using a web browser and broadcast that window.

The difficulty is that the round tracker pops up in front of the tokens, and since it's not my main focus I often don't move it out of the way or close it until after the combat is over. 

I would like to disable that feature for that ONE user, but the other users definitely appreciate that the round tracker pops up. It's a great feature for everyone else.  ( I figure it would be like the per-user volume configuration)

Thanks.

**Comment by ironmonk88** [comment]
Version 1.0.7 has the option to disable the popout on an individual basis.
Just been released.

**Comment by hoshisabi** [comment]
Excellent, just tried it out and works perfectly. :)
