### ISSUE TITLE
Feature Request: Check for Hidden Initiative and disable Next Turn

### ISSUE THREAD

**Issue by Tupsi** [ironmonk88/monks-little-details#90]
Hidden Initiative lets you hide the real initiative numbers behind ?. So in the first round you only know when it is your turn when it is your turn. The "Next Turn" sound and notification option of MLD is in the way of that feature, as it warns you one actor to soon of your near turn. At first I thought to just disable it completely on the GM end, but then I saw that its an individual option of every player.

It would be awesome if you could check for the Hidden Initiative module and honour it in the first round of combat, meaning hard disable/ignore both notification sound and message and only show/play it in rounds 2+.

**Comment by ironmonk88** [comment]
Added to the latest release.
