### ISSUE TITLE
CR Calculator not making sensible calculations

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-little-details#98]
For some reason CR will always calculate one rank below where it should be. If I put a single NPC marked as CR 6 on the map up against a single, two, four, or six Level 1, 2, 3, or whatever players, it always shows as CR 5. If I then add a CR 3 enemy, it increases by 2 points to CR 7. If I remove the CR 6 enemy, it drops down to CR2. No matter what it's one point below what it should be.

**Comment by ironmonk88** [comment]
It looks like it wasn't calculating correctly for single creatures.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
